### ISSUE TITLE
Add pymysql in Dockerfile for supporting mysql as the alternative database. And drop the foreign key contract.

### ISSUE THREAD

**Issue by syhily** [talebook/talebook#123]
SQLite3 would meet performance issues and database lock in huge book servers. Can you add pymysql when building the docker image? I have successfully migrated my talebook instance to MySQL. Everything works fine.

**Comment by syhily** [comment]
I have created a docker image `syhily/talebook:latest` on top of your image. This issue could be closed now.

**Comment by talebook** [comment]
It's welcome for PR.
But I guess the performance of the calibre db `metadata.db` is the key point, which is not easy to be migrated to mysql

**Comment by syhily** [comment]
After digging into the table structure. I'm quite curious about the `foreign key contract. This would influence the writing performance for `calibre-webserver.db`. The lock would occur because the disk isn't fast enough in NAS.

**Comment by syhily** [comment]
I would kindly ask not to add the [ForeignKey](https://github.com/talebook/talebook/blob/55d7fceb3a8c00f12122893b9988274b9ea5758b/webserver/models.py#L242) for all the tables. It's not required for non-enterprise projects such as talebook.
