### ISSUE TITLE
在线阅读ios15.3需要翻墙环境

### ISSUE THREAD

**Issue by undermoonoldman** [talebook/talebook#125]
iPhone13 Pro 在 ios 15.3 下无法在线阅读，一直处于页面加载中，无论内网还是公网访问。开启全局翻墙后公网在线阅读可以正常载入。服务端版本为最新3.1.47，群晖Docker部署

**Comment by sfcboy** [comment]
你用群晖docker没出错吗

**Comment by undermoonoldman** [comment]
> 你用群晖docker没出错吗

正常的

**Comment by gzsxy** [comment]
> 你用群晖docker没出错吗

作者已经修复并在docker hub更新了镜像，使用群晖docker部署3.1.48即可。

**Comment by talebook** [comment]
> iPhone13 Pro 在 ios 15.3 下无法在线阅读，一直处于页面加载中，无论内网还是公网访问。开启全局翻墙后公网在线阅读可以正常载入。服务端版本为最新3.1.47，群晖Docker部署

在线阅读功能不依赖外部能力，所以与网络应该没有啥关系。可以具体看看后台 talebook.log的Error报错信息。
我自己的网站上，ios 15.3试了下也是正常。

**Comment by undermoonoldman** [comment]
好的，谢谢，我再去看看日志
