### ISSUE TITLE
电脑软件calibre，怎么正确链接到docker目录 以实现电脑端批量管理图书

### ISSUE THREAD

**Issue by jk2008chd** [talebook/talebook#145]
电脑软件选择书库路径，不管选哪一个 包括calibre-web\books 都会提示数据库损坏要不要修复

**Comment by jk2008chd** [comment]
\\192.168.123.1\sdb\docker\calibre-web\books\library
![微信截图_20220403104426](https://user-images.githubusercontent.com/69377458/161408919-79b98caa-17ea-499c-ab01-fc3ee627ae5a.png)

**Comment by jk2008chd** [comment]
![image](https://user-images.githubusercontent.com/69377458/161442071-8fb47623-793b-46c0-bd7e-5d7d8232d3bf.png)
是因为文件权限原因吗还是什么

**Comment by jk2008chd** [comment]
已找到此问题的解决方案。停止docker后 可用桌面calibre进行批量书库整理
docker运行期间不知道是不是以为权限问题导致桌面calibre无法正确调用书库 也无法导入图书。
根本原因未知， 另一台群辉没有任何问题很稳定。 这一台openwrt就问题百出

**Comment by talebook** [comment]
io error一般是权限异常，或者磁盘硬件问题。你可以执行stat filepath 命令查查文件权限，例如检查下是不是归属给root了，别的用户无法操作
