### ISSUE TITLE
需要一个页面用于显示所有图书

### ISSUE THREAD

**Issue by parasomn1a** [talebook/talebook#147]
首先感谢作者对项目的辛勤奉献!

有注意到可能和这个问题重复的 [issue](https://github.com/talebook/talebook/issues/6), 但是侧重点不同故重新提一个.

需求是能有一个用于显示所有图书的页面, 并可以分页.

话说没有找到一份用于说明 「推荐的使用方式」的说明文档, 如果没有我很乐意补充.

**Comment by talebook** [comment]
嗯，的确是有必要提供一个表格式的管理界面。已经在计划中了。

关于使用说明指南，我一直没有空写文档，如果你能帮忙撰写那就太好了，感谢。

**Comment by talebook** [comment]
补充说明下，最近的开发计划是，1，先开发书籍批量导入的功能；2，导入完毕后，就是表格式批量修改书籍信息的表格。估计这周末能启动开发，4月会开发好初版。

**Comment by talebook** [comment]
`v3.5.6`版本已经支持表格式管理全部书籍。
