### ISSUE TITLE
Add MySQL support for talebook's database.

### ISSUE THREAD

**Issue by syhily** [talebook/talebook#151]
Talebook is support MySQL out of box because of the SQLAcademy. I have used MySQL for my personal website https://read.yufan.run by using a self maintained [Dockerfile](https://gist.github.com/syhily/d05770ee5e09ca6875cda80c73b07725).

Can you add pymysql to Dockerfile and add custom database support for talebook?
Add expose pool size for the `create_engine`

**Comment by talebook** [comment]
pymysql is ok.
sqlalchemy create_engine args will be provided in settings.py.

**Comment by syhily** [comment]
Thanks for your help. This will help me a lot.

**Comment by syhily** [comment]
@talebook I have used the `talebook/talebook:master` for the MySQL support. Everything works fine. But the database configuration would be overridden by default when creating a docker instance. Can we also expose the database setting on talebook install page?

**Comment by talebook** [comment]
you can put the configs into `/data/books/settings/manual.py`

**Comment by syhily** [comment]
OK, this works.
