### ISSUE TITLE
账号管理权限问题。

### ISSUE THREAD

**Issue by jk2008chd** [talebook/talebook#152]
我手贱，在用户设置页面点错到取消管理员权限。 再也无法登陆用户管理设置页面。另外，我没有找到删除多余账户的选项，请问怎么对其他账户进行删除操作？

**Comment by talebook** [comment]
1、丢失管理员权限的问题，只能手动修改配置`/data/books/settings/auto.py`，把`installed`改为`False`，重新走一次安装过程（会重置admin账号的权限和密码）；
2、用户删除功能正在开发中；

**Comment by jk2008chd** [comment]
请问有办法可以从后台手动删除用户吗？

**Comment by jk2008chd** [comment]
![image](https://user-images.githubusercontent.com/69377458/162708975-c926719c-e1fa-4513-a344-9a2ba0ebcb3a.png)
按您的方式重新走了一遍安装过程。 结果缺少设置了先前的设置菜单 如图

**Comment by jk2008chd** [comment]
![image](https://user-images.githubusercontent.com/69377458/162709159-3db1f521-e971-457a-a0a2-dde0bcc0f670.png)
按您的方法设置，重新走了一遍安装配置， 之后缺少先前的设置选项

**Comment by talebook** [comment]
后台手段的话，用SQL直接操作`readers`表

**Comment by talebook** [comment]
> ![image](https://user-images.githubusercontent.com/69377458/162709159-3db1f521-e971-457a-a0a2-dde0bcc0f670.png) 按您的方法设置，重新走了一遍安装配置， 之后缺少先前的设置选项

之前是我记错了，当前的版本里，重新安装不会重置admin账户的信息。

**Comment by talebook** [comment]
`v3.5.6`之后已解决此问题。避免手抖；也能重新安装reset账号。
