### ISSUE TITLE
私人图书馆模式登录界面排版bug

### ISSUE THREAD

**Issue by gzsxy** [talebook/talebook#159]
私人图书馆模式登录界面排版bug。具体见下图
该怕排版不管在3.5.4-3.5.6都存在
表现为蓝色banner遮挡其他内容
![bug](https://user-images.githubusercontent.com/23026142/163764358-084b5603-7a8d-4d90-aaba-dc1c52f456dc.png)

**Comment by talebook** [comment]
试试 v3.5.8版本

**Comment by gzsxy** [comment]
好的
