### ISSUE TITLE
外网使用ipv6无法访问

### ISSUE THREAD

**Issue by Linyue-GitHub** [talebook/talebook#166]

**Comment by xnklerEd** [comment]
我这里测试也是

**Comment by talebook** [comment]
我测了下，如果docker启动时绑定了IPV6地址，那么是能够正常使用IPV6访问的。例如
`http://[2402:4e00:1013:2600:0:9640:281d:f540]:8080`

如果你使用了NGINX作为代理，可以增加监听IPV6地址：
```
    listen 80;
    listen 443 ssl;
    listen [::]:80;
    listen [::]:443 ssl;
```

**Comment by talebook** [comment]
demo站点`http://demo.talebook.org`也增加了IPV6地址

**Comment by hcp1227** [comment]
> 

请问这个是nginx 代理是在哪里配置文件里设置？
