### ISSUE TITLE
直接推送EPUB至kindle功能

### ISSUE THREAD

**Issue by jianyun8023** [talebook/talebook#167]
kindle邮箱已经支持直接推送EPUB格式到kindle，现在可否在推送epub书籍时，不再转换为mobi文件

**Comment by jianyun8023** [comment]
https://bookfere.com/post/967.html

**Comment by jianyun8023** [comment]
目前看可以推送成功，但是书籍会不显示封面

**Comment by syhily** [comment]
LGTM

**Comment by talebook** [comment]
欢迎提PR
> 目前可以EPUB推送成功，但是书籍不显示封面。所以这个功能是否值得支持呢？
> 
> 
> 
> 我改了下代码，需要的话可以合并。
> 
> 
> 
> https://github.com/jianyun8023/talebook/commit/8e905fd4626ceded12e68f8455fb97be90886bbc
