### ISSUE TITLE
解压失败

### ISSUE THREAD

**Issue by ccyuki** [talebook/talebook#170]
今天docker安装下载的最新版本：
1. 上传文件报错，路径不存在
     于是手动创建books/upload路径，通过；
     正常来说，这个目录应该会和其它library、extract等目录一起创建

2. 所有打开文件阅读，因为是第一次使用，都是首次阅读（不论是自带的，还是后上传的mobi, epub），所以会提示“首次阅读，服务器正在解压书籍，请等待约2分钟”，2分钟后，报错，"系统异常，请在QQ群里联系管理员"。
     后来翻看log，缺失process路径；
     创建后，解压，缺失convert路径；

以上三个路径，手工创建后，成功使用。

**Comment by talebook** [comment]
大概率是你挂载的目录已经有books文件夹了，所以没有自动创建子目录

**Comment by ccyuki** [comment]
> 
嗯有可能
