### ISSUE TITLE
新用户注册邮箱无法激活

### ISSUE THREAD

**Issue by vicjianling** [talebook/talebook#172]
用的是微软live邮箱，收到的激活邮件没有任何内容，只有邮件标题是欢迎注册文渊阁，不能激活就用不了发送到kindle的功能了，但用户管理里面也没有修改邮箱的选项，请问应该怎么解决呢？或者说目前支持什么邮箱注册呢？

**Comment by shentar** [comment]
大概率是live邮箱过滤了内容。建议先换个邮箱试试吧。

**Comment by vicjianling** [comment]
确实换了QQ邮箱注册账号就行了
