### ISSUE TITLE
douban关闭了tag导致的错误

### ISSUE THREAD

**Issue by Cheukfung** [talebook/talebook#174]
感谢作者的付出。
因为豆瓣的标签事件，书籍和电影都关闭了tag显示，书籍用豆瓣meta插件更新就会出错
douban.py获取不到tag就抛出异常了，也没处理异常，更新信息就会失败。
错误在159行：
` mi.tags = [t["name"] for t in book["tags"]][:8]`
直接注释那一行或者try except应该就可以了
本人才疏学浅就不提pr了

**Comment by shentar** [comment]
你用的哪个版本，最新版本应该是没问题的。

**Comment by Cheukfung** [comment]
3.5.6

**Comment by Cheukfung** [comment]
没好好看文档，没问题了
