### ISSUE TITLE
推送至kindle能否指定格式，不要自动转换为mobi

### ISSUE THREAD

**Issue by gray0128** [talebook/talebook#178]
从2022年末起，您将无法再使用〖发送至Kindle〗将MOBI（.AZW、.MOBI）文件发送至您的图书馆。此更改不会影响任何已在您的Kindle图书馆中的MOBI文件。MOBI是较旧的文件格式，不支持适用于文档的最新Kindle功能。

https://www.amazon.cn/gp/help/customer/display.html/ref=kinw_myk_wl_ln?ie=UTF8&nodeId=200767340#pdocarchive

**Comment by talebook** [comment]
打算先改为epub格式
