### ISSUE TITLE
邮件推送kindle失败

### ISSUE THREAD

**Issue by captainlihang** [talebook/talebook#179]
邮件服务更改为自有地址后测试成功，成功发送了一次，后续均不成功，求解！

**Comment by talebook** [comment]
1、请贴talebook.log文件；
2、检查下发件箱是否有记录；
3、如果是自己VPS搭建的邮箱服务，请联系客服检查25端口的可用性；

**Comment by gzsxy** [comment]
亚马逊对不是常用的邮箱后缀有一个验证机制，建议看看你的邮箱是否收到了亚马逊验证邮件。

**Comment by captainlihang** [comment]
感谢各位老大的建议，问题已经解决。
1）亚马逊验证机制没问题，第一次尝试就成功了，后续几次都不行，而且从我的邮箱发件箱中没有收到相关邮件；
2）端口25没有问题；
3）后来我直接重启了docker，然后就正常了。
再次表示感谢。
