### ISSUE TITLE
arm64版本安装失败

### ISSUE THREAD

**Issue by xnklerEd** [talebook/talebook#180]
两台测试机器，一台商业nas，安装talebook完美运行，目测应该是x86平台，因为cpu是赛扬 J425，启动成功日志：

> e2022-05-13T04:56:56.000129601Z [I 220513 04:56:55 main:124] Init library with [/data/books/library/]
> {2022-05-13T04:56:56.000344163Z [I 220513 04:56:55 main:125] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
> v2022-05-13T04:56:56.000454756Z [I 220513 04:56:56 main:126] Init Static  with [/var/www/talebook/webserver/resources]
> x2022-05-13T04:56:56.000540446Z [I 220513 04:56:56 main:127] Init HTML    with [/var/www/talebook/webserver/../app/dist]
> x2022-05-13T04:56:56.000613506Z [I 220513 04:56:56 main:128] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
> T2022-05-13T04:56:56.127850161Z [I 220513 04:56:56 models:41] Bind modles._session()
> R2022-05-13T04:56:56.160730197Z [I 220513 04:56:56 main:147] Create tables into DB
> e2022-05-13T04:56:58.806242962Z [I 220513 04:56:58 main:124] Init library with [/data/books/library/]
> {2022-05-13T04:56:58.806400965Z [I 220513 04:56:58 main:125] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
> v2022-05-13T04:56:58.806525799Z [I 220513 04:56:58 main:126] Init Static  with [/var/www/talebook/webserver/resources]
> x2022-05-13T04:56:58.806625851Z [I 220513 04:56:58 main:127] Init HTML    with [/var/www/talebook/webserver/../app/dist]
> x2022-05-13T04:56:58.806709482Z [I 220513 04:56:58 main:128] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
> Q2022-05-13T04:56:58.806788847Z [I 220513 04:56:58 main:131] updating configs ...
> A2022-05-13T04:56:59.019573732Z [I 220513 04:56:59 main:136] done
> 82022-05-13T04:57:01.474612185Z Restarting nginx: nginx.
> 2022-05-13T04:57:08.239941341Z 2022-05-13 04:57:08,239 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
> �2022-05-13T04:57:08.254983427Z 2022-05-13 04:57:08,254 INFO Included extra file "/etc/supervisor/conf.d/talebook.conf" during parsing
> c2022-05-13T04:57:08.714404344Z 2022-05-13 04:57:08,714 INFO RPC interface 'supervisor' initialized
> �2022-05-13T04:57:08.729379400Z 2022-05-13 04:57:08,729 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> \2022-05-13T04:57:08.731010433Z 2022-05-13 04:57:08,730 INFO supervisord started with pid 32
> [2022-05-13T04:57:09.735276385Z 2022-05-13 04:57:09,734 INFO spawned: 'tornado' with pid 33
> Z2022-05-13T04:57:09.745854295Z 2022-05-13 04:57:09,744 INFO spawned: 'nodejs' with pid 34
> �2022-05-13T04:57:10.769019276Z 2022-05-13 04:57:10,748 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> �2022-05-13T04:57:10.769381444Z 2022-05-13 04:57:10,769 INFO success: nodejs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

另外一台是N1盒子，arm64架构的，安装后打开192.168.1.8:8080 显示server error，特意看了下，挂载到/data目录的外部目录已经有成功生成的书库以及测试书籍。所以应该也不是目录权限问题。启动日志：

> `
> [I 220513 13:12:24 main:124] Init library with [/data/books/library/],
> [I 220513 13:12:24 main:125] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db],
> [I 220513 13:12:24 main:126] Init Static  with [/var/www/talebook/webserver/resources],
> [I 220513 13:12:24 main:127] Init HTML    with [/var/www/talebook/webserver/../app/dist],
> [I 220513 13:12:24 main:128] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env],
> [I 220513 13:12:24 models:41] Bind modles._session(),
> [I 220513 13:12:24 main:147] Create tables into DB,
> [I 220513 13:12:27 main:124] Init library with [/data/books/library/],
> [I 220513 13:12:27 main:125] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db],
> [I 220513 13:12:27 main:126] Init Static  with [/var/www/talebook/webserver/resources],
> [I 220513 13:12:27 main:127] Init HTML    with [/var/www/talebook/webserver/../app/dist],
> [I 220513 13:12:27 main:128] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env],
> [I 220513 13:12:27 main:131] updating configs ...,
> [I 220513 13:12:27 main:136] done,
> Restarting nginx: nginx.,
> 2022-05-13 13:12:30,462 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.,
> 2022-05-13 13:12:30,462 INFO Included extra file "/etc/supervisor/conf.d/talebook.conf" during parsing,
> 2022-05-13 13:12:30,483 INFO RPC interface 'supervisor' initialized,
> 2022-05-13 13:12:30,484 CRIT Server 'unix_http_server' running without any HTTP authentication checking,
> 2022-05-13 13:12:30,486 INFO supervisord started with pid 28,
> 2022-05-13 13:12:31,499 INFO spawned: 'tornado' with pid 29,
> 2022-05-13 13:12:31,513 INFO spawned: 'nodejs' with pid 30,
> 2022-05-13 13:12:32,518 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2022-05-13 13:12:32,519 INFO success: nodejs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2022-05-13 13:12:47,887 INFO exited: tornado (exit status 1; not expected),
> 2022-05-13 13:12:48,271 INFO spawned: 'tornado' with pid 54,
> 2022-05-13 13:12:49,275 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2022-05-13 13:13:03,538 INFO exited: tornado (exit status 1; not expected),
> 2022-05-13 13:13:04,555 INFO spawned: 'tornado' with pid 56,
> 2022-05-13 13:13:05,559 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2022-05-13 13:13:19,648 INFO exited: tornado (exit status 1; not expected),
> 2022-05-13 13:13:20,708 INFO spawned: 'tornado' with pid 58,
> 2022-05-13 13:13:21,680 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),'

后续做了一下排除测试，但是问题仍然没有解决：
将成功安装后的那台机器上的talebook停止，然后把生成的数据文件夹拷贝到N1盒子上，重新挂载为/data
启动，仍然显示server error
以上都是使用的talebook/talebook:latest ，换用 talebook/talebook:master 问题依旧。

**Comment by talebook** [comment]
需要提供下 /data/log/talebook.log

**Comment by xnklerEd** [comment]
> 

抱歉我昨天的描述不够准确，并且昨天测试失败后没保存，今天重复操作一次，我再补充描述一下操作遇到的问题：
nas有运行着的书库，最近nas出了些问题打算把书库迁移一下，于是在这n1盒子上执行了一次全新安装后停止并删除了外部目录下的/book/library 书库目录，然后把nas上的/book/library目录先用samba的方式挂载到n1的/talebook/book/library然后重新启动容器，就复现了昨天的server error，下面是log文件。
[talebook.log](https://github.com/talebook/talebook/files/8692622/talebook.log)

**Comment by talebook** [comment]
应该是目录结构有变化导致的。我看log里提示没找到书库文件，尝试自动创建（然后失败退出了）

你可以再检查检查挂载的目录的参数，看看目录层级是否跟自动生成的一致

**Comment by xnklerEd** [comment]
谢谢，今天又重新安装后导入书库一次，先导入library下的所有文件进行覆盖，然后导入上一级目录的calibre数据库文件覆盖，然后启动docker，成功。非常感谢作者的频繁更新。
