### ISSUE TITLE
密码访问页面bug

### ISSUE THREAD

**Issue by gzsxy** [talebook/talebook#185]
![微信截图_20220520093346](https://user-images.githubusercontent.com/23026142/169431124-c801bbca-9b7a-4be9-b85a-444083e07dab.png)
之前反馈过该页面bug，目前依然存在，版本为3.5.8

**Comment by gzsxy** [comment]
具体体现为蓝色banner挡住下方内容

**Comment by talebook** [comment]
我这边一直无法复现该问题。请提供下你的浏览器版本、站点URL

**Comment by gzsxy** [comment]
请留一个联系方式，私发给你

**Comment by talebook** [comment]
talebook@foxmail.com

**Comment by talebook** [comment]
已查明原因并修复

**Comment by gzsxy** [comment]
感谢作者的辛苦付出
