### ISSUE TITLE
已经在logo文件夹中替换了icon和link的图标，但前端还是原来的没变。

### ISSUE THREAD

**Issue by NeedforGit** [talebook/talebook#192]
感谢在新版本中添加了可更换的 logo 文件夹。
我已经在logo文件夹中替换了icon和link的图标，但前端还是原来的没变。
Docker 也已经重启了，请问如何解决？
多谢！

**Comment by talebook** [comment]
试试清除浏览器缓存

**Comment by NeedforGit** [comment]
试了，清楚了缓存还是不行。

请看下图中，已经成功替换了图片

https://pic.imgdb.cn/item/62a0303b0947543129d3525f.jpg

但前端还是原来的图片。

**Comment by wugusu** [comment]
也有同样问题

**Comment by GaryNotGay** [comment]
本人亲测，需要手动进虚机，将/var/www/talebook/app/src/static/logo这个路径下的两个logo替换，并重启服务，就可以了

**Comment by NeedforGit** [comment]
最新的 Docker 版本3.6.0 亲测已经解决了这个问题！感谢！
