### ISSUE TITLE
如何修改网页标题

### ISSUE THREAD

**Issue by flashlab** [talebook/talebook#203]
设置里已经设定了网站标题，但只有左上角显示正确，网页标题（也就是head标签里的title）依然是“奇异书屋：，请问这个有办法修改吗？或者哪里可以手动更改呢？

**Comment by GaryNotGay** [comment]
我是清缓存+重启虚机以后才OK的

**Comment by flashlab** [comment]
重启有效，感谢

> 我是清缓存+重启虚机以后才OK的
