### ISSUE TITLE
链接Opds，出现这个提示，请问是什么意思啊？

### ISSUE THREAD

**Issue by caonima1198** [talebook/talebook#206]
之前好像曾经可以用，现在用不了了。
![Screenshot_2022-07-09-21-43-56-65_9bd6c70c72493002d79393234a2b3cbd](https://user-images.githubusercontent.com/85956047/178108625-4ccb3c3e-c574-4989-bb03-de578b84a508.jpg)

**Comment by talebook** [comment]
URL地址的末尾增加个斜杠。例如 `http://demo.talebook.org/opds/`
