### ISSUE TITLE
docker 导入图书-扫描书籍提示【参数错误】

### ISSUE THREAD

**Issue by 8Hq7e** [talebook/talebook#208]
手动将书籍目录挂载到/ebookdata 目录下，在【高级配置项-设置批量导入扫描目录】为/ebookdata，【管理-导入图书】提示为：请将需要导入的书籍放入/ebookdata目录中。但是点击扫描书籍提示参数错误。
此目录下只有一本测试图书：要钱还是要生活.epub

**Comment by talebook** [comment]
为了系统安全，目录必须是`/data/` 下，例如`/data/ebookdata`
