### ISSUE TITLE
阅读时出现文字重叠

### ISSUE THREAD

**Issue by voctot** [talebook/talebook#225]
第一次打开文字不会重叠，如果退出在打开就会出现文字重叠。

**Comment by voctot** [comment]
![1661855510917](https://user-images.githubusercontent.com/36097179/187415963-8d9d9d2f-45e1-41d3-9f0b-cf060d7a8b88.jpg)

**Comment by juiiz** [comment]
遇到同样问题，请问有解决吗

**Comment by voctot** [comment]
> 遇到同样问题，请问有解决吗

切换成其它背景颜色这个bug能得到解决。

**Comment by juiiz** [comment]
> > 遇到同样问题，请问有解决吗
> 
> 切换成其它背景颜色这个bug能得到解决。

已解决，感谢

**Comment by talebook** [comment]
新版readiumjs引入的BUG。在 v3.6.1 版本中已回滚，应该恢复正常了。

**Comment by voctot** [comment]
> 新版readiumjs引入的BUG。在 v3.6.1 版本中已回滚，应该恢复正常了。

3.6.1是时候发布？
