### ISSUE TITLE
【bug】注册页面报错，且没有成功发送注册邮件给新用户

### ISSUE THREAD

**Issue by Pan06da** [talebook/talebook#238]
管理员账户操作时：在高级设置页面内按照前端页面提示进行了smtp配置，点击测试邮件，能够在页面获取成功提示，并且在能够成功在邮箱中收到测试邮件。

推出管理员账户，在登陆页面选择新注册账户，会出现前端页面报错。

重新登陆管理员账户，在用户管理中显示用户已经注册信息，只是未激活。

<img width="491" alt="image" src="https://user-images.githubusercontent.com/93591234/192918789-7a944471-cced-4524-8711-a536f4a7eb9b.png">

**Comment by talebook** [comment]
看提示，User has no permission，用户无权限登录。你这是用的是什么邮箱？

**Comment by mingqing007** [comment]
遇到同样的问题，注册报错，可以登录，但是登录后依然无法验证邮箱，qq 邮箱 和 gmail 都不可以。
