### ISSUE TITLE
同书籍名的两个文件如何导入

### ISSUE THREAD

**Issue by UltramarineSky** [talebook/talebook#242]
同一书籍有两个不同出版社的版本，内容也有些区别，想要导入进去，提示已存在，请问有什么方法可以导入吗

**Comment by UltramarineSky** [comment]
https://github.com/talebook/talebook/issues/12#issuecomment-502536782
看到以前回应的为了减少存储空间而不支持同一书名上传多个版本，但现在很多人都是用nas部署保存的，存储空间限制应该还好。
很多书有不同译者、出版社不同的版本，每个版本都有自己的特色，比如《新教伦理与资本主义精神》这本书我收集到的就有两个版本，比较好的有两个版本，一个的译文比较好，但缺少了原作者注，一个有原作者注但译文不是很好，要是能都保存就好
希望可以加个开关设置项让想要保存多版本多格式的用户可以保存

**Comment by fuhao3503** [comment]
> 同一书籍有两个不同出版社的版本，内容也有些区别，想要导入进去，提示已存在，请问有什么方法可以导入吗

我的做法是在书名后面加上备注（比如出版年份，出版社，或者第几版），这样的话，再配合ISBN，就没有问题了。
