### ISSUE TITLE
关于豆瓣插件刮削的问题

### ISSUE THREAD

**Issue by Linyue-GitHub** [talebook/talebook#264]
![-53abf3d42531865c](https://user-images.githubusercontent.com/71179298/208626703-250cb0dd-8e44-49ab-a873-889fc2ffc7b7.jpg)
插件日志刮削提示404，书库这边刮削不了豆瓣数据，有没有大佬看看是什么问题。

**Comment by talebook** [comment]
https://github.com/talebook/talebook/blob/master/document/README.zh_CN.md#%E5%A6%82%E6%9E%9C%E9%85%8D%E7%BD%AE%E8%B1%86%E7%93%A3%E6%8F%92%E4%BB%B6

**Comment by talebook** [comment]
https://github.com/talebook/talebook/blob/master/document/README.zh_CN.md#%E5%A6%82%E6%9E%9C%E9%85%8D%E7%BD%AE%E8%B1%86%E7%93%A3%E6%8F%92%E4%BB%B6
请参考帮助说明中的这节内容

**Comment by Linyue-GitHub** [comment]
> https://github.com/talebook/talebook/blob/master/document/README.zh_CN.md#%E5%A6%82%E6%9E%9C%E9%85%8D%E7%BD%AE%E8%B1%86%E7%93%A3%E6%8F%92%E4%BB%B6 请参考帮助说明中的这节内容

就是按照帮助上面设置的，只不过没用docker compose 独立安装的容器
