### ISSUE TITLE
使用QQ邮箱无法发送激活邮件

### ISSUE THREAD

**Issue by wangxiushen92** [talebook/talebook#266]
使用QQ邮箱无法发送激活邮件

**Comment by wwwaaannngggg** [comment]
我也是

**Comment by Aruku448** [comment]
俺也一样

**Comment by talebook** [comment]
QQ邮箱是不是直接使用了QQ密码？需要进入QQ邮箱的【设置】，在【账户】页面下找到【POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务】这段，生成`授权码`进行使用。

**Comment by luo-chuan** [comment]
> QQ邮箱是不是直接使用了QQ密码？需要进入QQ邮箱的【设置】，在【账户】页面下找到【POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务】这段，生成`授权码`进行使用。

试过了，没用
