### ISSUE TITLE
v3.6.3 版本引入了PDF.js 在线阅读功能异常

### ISSUE THREAD

**Issue by sqlsec** [talebook/talebook#280]
换了几个 Chrome 内核的浏览器都测试无法正常访问：

![](https://user-images.githubusercontent.com/25379234/221524987-05541f8b-76cc-42f9-aa98-e4e4263616ce.jpg)

发现是 PDF.js 加载问题

<img width="911" alt="image" src="https://user-images.githubusercontent.com/25379234/221526746-84b11d9f-6c1a-4dcf-b5e5-a554b18d1fa8.png">

所以目前回退了 3.6.2 版本发现是正常的

**Comment by jsczrangel** [comment]
同问，源码里都没有这个文件

**Comment by ccsirer** [comment]
已退回3.6.2
