### ISSUE TITLE
关于pdf阅读逻辑问题

### ISSUE THREAD

**Issue by Shenhyuu** [talebook/talebook#282]
开发者大大你好：
在使用过程中发现：若服务器带宽有限且pdf文件较大时，在线阅读加载极其缓慢。请问下有没有办法为pdf在线阅读器加入lazeload机制，逐页加载，避免网络堵塞？
谢谢！

**Comment by shentar** [comment]
@talebook 这里好像要支持pdf文件的range下载就好了。我在fork出去的分支上改了，但是分支跟主干差异太大了，合不过来 ^_^
下面这个是从StaticFileHandler里面copy过来的，不知道有没有更好的直接用这个代码的方法。
`    def range_get_pdf(self, path):
        self.set_header("Accept-Ranges", "bytes")
        request_range = None
        range_header = self.request.headers.get("Range")
        if range_header:
            # As per RFC 2616 14.16, if an invalid Range header is specified,
            # the request will be treated as if the header didn't exist.
            request_range = httputil._parse_request_range(range_header)

        file_stat = os.stat(path)
        size = file_stat.st_size

        if request_range:
            start, end = request_range
            if start is not None and start < 0:
                start += size
                if start < 0:
                    start = 0
            if (start is not None
                and (start >= size or (end is not None and start >= end))) \
                    or end == 0:
                # As per RFC 2616 14.35.1, a range is not satisfiable only: if
                # the first requested byte is equal to or greater than the
                # content, or when a suffix with length 0 is specified.
                # https://tools.ietf.org/html/rfc7233#section-2.1
                # A byte-range-spec is invalid if the last-byte-pos value is present
                # and less than the first-byte-pos.
                self.set_status(416)  # Range Not Satisfiable
                self.set_header("Content-Type", "text/plain")
                self.set_header("Content-Range", "bytes */%s" % (size,))
                return
            if end is not None and end > size:
                # Clients sometimes blindly use a large range to limit their
                # download size; cap the endpoint at the actual file size.
                end = size
            # Note: only return HTTP 206 if less than the entire range has been
            # requested. Not only is this semantically correct, but Chrome
            # refuses to play audio if it gets an HTTP 206 in response to
            # ``Range: bytes=0-``.
            if size != (end or size) - (start or 0):
                self.set_status(206)  # Partial Content
                self.set_header("Content-Range", httputil._get_content_range(start, end, size))
        else:
            start = end = None

        if start is not None and end is not None:
            content_length = end - start
        elif end is not None:
            content_length = end
        elif start is not None:
            content_length = size - start
        else:
            content_length = size
        self.set_header("Content-Length", content_length)

        content = web.StaticFileHandler.get_content(path, start, end)
        if isinstance(content, bytes):
            content = [content]
        for chunk in content:
            self.write(chunk)
`

**Comment by talebook** [comment]
过一阵子我测测看

> @talebook 这里好像要支持pdf文件的range下载就好了。我在fork出去的分支上改了，但是分支跟主干差异太大了，合不过来 ^_^
> 
> 下面这个是从StaticFileHandler里面copy过来的，不知道有没有更好的直接用这个代码的方法。
> 
> ```def range_get_pdf(self, path):
> 
>         self.set_header("Accept-Ranges", "bytes")
> 
>         request_range = None
> 
>         range_header = self.request.headers.get("Range")
> 
>         if range_header:
> 
>             # As per RFC 2616 14.16, if an invalid Range header is specified,
> 
>             # the request will be treated as if the header didn't exist.
> 
>             request_range = httputil._parse_request_range(range_header)
> 
> 
> 
>         file_stat = os.stat(path)
> 
>         size = file_stat.st_size
> 
> 
> 
>         if request_range:
> 
>             start, end = request_range
> 
>             if start is not None and start < 0:
> 
>                 start += size
> 
>                 if start < 0:
> 
>                     start = 0
> 
>             if (start is not None
> 
>                 and (start >= size or (end is not None and start >= end))) \
> 
>                     or end == 0:
> 
>                 # As per RFC 2616 14.35.1, a range is not satisfiable only: if
> 
>                 # the first requested byte is equal to or greater than the
> 
>                 # content, or when a suffix with length 0 is specified.
> 
>                 # https://tools.ietf.org/html/rfc7233#section-2.1
> 
>                 # A byte-range-spec is invalid if the last-byte-pos value is present
> 
>                 # and less than the first-byte-pos.
> 
>                 self.set_status(416)  # Range Not Satisfiable
> 
>                 self.set_header("Content-Type", "text/plain")
> 
>                 self.set_header("Content-Range", "bytes */%s" % (size,))
> 
>                 return
> 
>             if end is not None and end > size:
> 
>                 # Clients sometimes blindly use a large range to limit their
> 
>                 # download size; cap the endpoint at the actual file size.
> 
>                 end = size
> 
>             # Note: only return HTTP 206 if less than the entire range has been
> 
>             # requested. Not only is this semantically correct, but Chrome
> 
>             # refuses to play audio if it gets an HTTP 206 in response to
> 
>             # ``Range: bytes=0-``.
> 
>             if size != (end or size) - (start or 0):
> 
>                 self.set_status(206)  # Partial Content
> 
>                 self.set_header("Content-Range", httputil._get_content_range(start, end, size))
> 
>         else:
> 
>             start = end = None
> 
> 
> 
>         if start is not None and end is not None:
> 
>             content_length = end - start
> 
>         elif end is not None:
> 
>             content_length = end
> 
>         elif start is not None:
> 
>             content_length = size - start
> 
>         else:
> 
>             content_length = size
> 
>         self.set_header("Content-Length", content_length)
> 
> 
> 
>         content = web.StaticFileHandler.get_content(path, start, end)
> 
>         if isinstance(content, bytes):
> 
>             content = [content]
> 
>         for chunk in content:
> 
>             self.write(chunk)
> 
> ```
> 
>

**Comment by xflcx1991** [comment]
@talebook 我来催更了，请问是否有眉目，在线观看要先完整下完，这似乎失去了网页——“流”的优势。

**Comment by geekidentity** [comment]
@talebook  催更，PDF逐页加载太有必要了
