### ISSUE TITLE
这里应该有session泄露了，新线程里面申请是session没有close和remove

### ISSUE THREAD

**Issue by shentar** [talebook/talebook#283]
https://github.com/talebook/talebook/blob/09851f643057b109631f5b9bc5b99fd9a740b96b/webserver/handlers/scan.py#L74

**Comment by talebook** [comment]
https://docs.sqlalchemy.org/en/20/orm/contextual.html#thread-local-scope
> So it is in fact “safe” to use thread local scope with an application that spawns and tears down threads, without the need to call `scoped_session.remove()`.

@shentar  根据文档，会自动释放。Python就是这点好，各种玩法溜得很。

**Comment by shentar** [comment]
这里每运行一段时间就会提醒连接池超限了，我是在线程退出时加了session.close和remove，就没再出了。我也查了很多这样的说明，那可能是close起作用。

**Comment by shentar** [comment]
会报错，然后界面不响应。可以试下反复触发后台线程的情况。

**Comment by talebook** [comment]
。。。既然有坑，那我后面再加上个close吧

**Comment by talebook** [comment]
@shentar 帮忙review下最新的代码，应该在哪儿加close？ 距离之前的讨论已经过了大半年，忘得一干二净了 😂

**Comment by shentar** [comment]
> @shentar 帮忙review下最新的代码，应该在哪儿加close？ 距离之前的讨论已经过了大半年，忘得一干二净了 😂

就是在调用bind_new_session的线程退出时显式调用一次remove_session。
