### ISSUE TITLE
小白问一下CDN域名有什么用？如何配置

### ISSUE THREAD

**Issue by whitewatercn** [talebook/talebook#285]
CDN已经配置好了，网站可以正常使用，请问这个CDN域名有什么用？如何配置？直接复制图里的域名吗？
![image](https://user-images.githubusercontent.com/58654928/225592202-a945eb63-ffdc-431f-99f2-7fef79966895.png)

但如果这么操作的话，图书封面、下载等功能就会无法使用
![image](https://user-images.githubusercontent.com/58654928/225592746-9ff217d2-8016-4ab1-8c71-13520d9cc5a5.png)
![image](https://user-images.githubusercontent.com/58654928/225592809-d2f642aa-ba85-4901-b468-bed1177342a1.png)

**Comment by talebook** [comment]
cdn域名主要用于公共书库时优化访问性能，减少访问压力。个人书库（以及访问量小的）可以不启用。

具体使用时，需要做『动静分级』（如果不懂该词含义，可以到各大公有云平台搜索学习下）。具体来说：
1. 准备两个域名，比如说book.qq.xom和cdn.qq.com
2. 把book.qq.com的DNS指向talebook服务器，确保能正常访问整站；
3. 到阿里云CDN上添加cdn.qq.com并配置源站为book.qq.com，回源域名也填写为book.qq.com；阿里云会显示CNAME（就是你截图中红框的那个），你需要配置好DNS记录。
4. 此时，直接访问cdn.qq.com域名应该也是能正常打开的（但实际上图片还是访问为book.qq.com）
5. 最后一步，在talebook后台配置CDN域名为cdn.qq.com

这时候使用cdn域名或者book域名均可访问了
