### ISSUE TITLE
曾经打开的图书，不能再打开了显示404

### ISSUE THREAD

**Issue by zking0914** [talebook/talebook#291]
曾经打开过的图书，打不开了，显示“404: 抱歉，在线阅读器暂不支持该格式的书籍“（格式有epub，azw3）。同时，在图书信息页上没有封面，但是在图书管理里有封面。而且是选择性的显示不了，就是我同一天上传的3本书，同一个格式，有的还能打开，有的就不能了。

最新的两个版本，都测试了，都有问题。我是从上一版本更新到最新版本的。

**Comment by Nothend** [comment]
我的也有类似情况，是提示：该文件可能已被移至别处、修改或删除。部分epub格式的书，无法在线阅读。在kindle上是可以的。导入calibre也是可以阅读

**Comment by talebook** [comment]
这种情况就是：实际的文件目录可能有问题，或者被改名or删了。
