### ISSUE TITLE
该文件可能已被移至别处、修改或删除

### ISSUE THREAD

**Issue by Nothend** [talebook/talebook#294]
![image](https://user-images.githubusercontent.com/73117056/232361679-4c4048d2-8357-4046-98d8-71ba0b36cb5c.png)

部分epub格式的书，无法在线阅读，没有封面。在kindle上是可以的。导入calibre也是可以阅读，通过OPDS导入kyBook 3 也可以阅读，有封面

**Comment by talebook** [comment]
请提供下epub文件

**Comment by Nothend** [comment]
> 请提供下epub文件

谢谢大佬回复，经过一番折腾，发现是谷歌浏览器的问题，重装浏览器之后好了。再次感谢
