### ISSUE TITLE
如何修改服务器时间？

### ISSUE THREAD

**Issue by HelloMusician** [talebook/talebook#295]
如题，导入书籍的时间与所在时区不符，如何调整

**Comment by shentar** [comment]
试一下这个，我好像是这么解决的。
docker创建时增加环境变量：
-e TZ="Asia/Shanghai"

**Comment by HelloMusician** [comment]
> 试一下这个，我好像是这么解决的。 docker创建时增加环境变量： -e TZ="Asia/Shanghai"

谢谢，成功了。
另外分类导航不显示书籍您遇到过吗

**Comment by shentar** [comment]
分类导航是根据书籍标签来匹配的。书籍没有打标签就不会显示。

**Comment by HelloMusician** [comment]
原来如此，多谢！！！

Tong Yanqun ***@***.***> 于2023年4月18日周二 12:02写道：
