### ISSUE TITLE
批量导入书籍只导入其中几本，日志如下

### ISSUE THREAD

**Issue by Aetco** [talebook/talebook#304]
docker版，Talebook版本为3.6.4。
导入数量为5本内可以正常全部导入，超过五本(差不多这数)开始则会出现这种情况。如果批量导入千本则会导入看似随机的其中几本到十几本。
刚好出错没有导入的地方日志如下。

[I 230519 02:55:59 scan:226] import [《国际条约集（1950-1952）》] from /data/books/imports/政治学/国际关系史/国际条约集/《国际条约集（1950-1952）》.pdf
[E 230519 02:55:59 scan:49] update: status=imported, path=/data/books/imports/政治学/国际关系史/国际条约集/《国际条约集（1950-1952）》.pdf [ book-id=685 ]
[D 230519 02:56:00 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:00 web:2239] 200 GET /api/lololo/import/status (172.17.0.1) 23.66ms
[I 230519 02:56:00 scan:226] import [后形而上学思想 ] from /data/books/imports/丛书/人文与社会译丛/【人文与社会译丛】51[德]于尔根·哈贝马斯：后形而上学思想.pdf
**Exception in thread do_import:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/talebook/webserver/handlers/scan.py", line 227, in do_import
    row.book_id = self.db.import_book(mi, [fpath])
  File "/usr/lib/calibre/calibre/db/legacy.py", line 362, in import_book
    book_ids, duplicates = self.new_api.add_books(
  File "/usr/lib/calibre/calibre/db/cache.py", line 1713, in add_books
    book_id = self.create_book_entry(mi, add_duplicates=add_duplicates, apply_import_tags=apply_import_tags, preserve_uuid=preserve_uuid)
  File "/usr/lib/calibre/calibre/db/cache.py", line 72, in call_func_with_lock
    return func(*args, **kwargs)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1683, in create_book_entry
    self._set_metadata(book_id, mi, ignore_errors=True)
  File "/usr/lib/calibre/calibre/db/cache.py", line 1396, in set_metadata
    self._update_path({book_id})
  File "/usr/lib/calibre/calibre/db/cache.py", line 1220, in update_path
    self.backend.update_path(book_id, title, author, self.fields['path'], self.fields['formats'])
  File "/usr/lib/calibre/calibre/db/backend.py", line 1649, in update_path
    os.makedirs(tpath)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
ValueError: embedded null byte**
[D 230519 02:56:02 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:02 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 22.16ms
[D 230519 02:56:02 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[D 230519 02:56:02 lololo:451] num=100, page=0, sort=id, desc=True
[D 230519 02:56:02 base:400] [  146 ms] select books from library  (count = 100)
[D 230519 02:56:02 base:417] [  167 ms] select books from database (count = 100)
[I 230519 02:56:02 web:2239] 200 GET /api/lololo/book/list?page=1&sort=id&desc=true&num=100&search= (172.17.0.1) 190.76ms
[I 230519 02:56:03 web:2239] 200 GET /get/thumb_60x80/684.jpg?t=1684464957 (172.17.0.1) 125.87ms
[I 230519 02:56:03 web:2239] 200 GET /get/thumb_60x80/685.jpg?t=1684464959 (172.17.0.1) 28.58ms
[D 230519 02:56:04 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:04 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 18.80ms
[D 230519 02:56:06 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[D 230519 02:56:06 lololo:451] num=100, page=0, sort=id, desc=True
[D 230519 02:56:06 base:400] [  152 ms] select books from library  (count = 100)
[D 230519 02:56:06 base:417] [  173 ms] select books from database (count = 100)
[I 230519 02:56:06 web:2239] 304 GET /api/lololo/book/list?page=1&sort=id&desc=true&num=100&search= (172.17.0.1) 196.45ms
[D 230519 02:56:06 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:06 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 18.61ms
[D 230519 02:56:07 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[D 230519 02:56:07 lololo:451] num=100, page=0, sort=id, desc=True
[D 230519 02:56:07 base:400] [  146 ms] select books from library  (count = 100)
[D 230519 02:56:07 base:417] [  166 ms] select books from database (count = 100)
[I 230519 02:56:07 web:2239] 304 GET /api/lololo/book/list?page=1&sort=id&desc=true&num=100&search= (172.17.0.1) 189.32ms
[D 230519 02:56:08 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:08 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 19.69ms
[D 230519 02:56:08 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[D 230519 02:56:08 lololo:451] num=100, page=0, sort=id, desc=True
[D 230519 02:56:08 base:400] [  145 ms] select books from library  (count = 100)
[D 230519 02:56:08 base:417] [  166 ms] select books from database (count = 100)
[I 230519 02:56:08 web:2239] 304 GET /api/lololo/book/list?page=1&sort=id&desc=true&num=100&search= (172.17.0.1) 189.05ms
[D 230519 02:56:09 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[D 230519 02:56:09 lololo:451] num=100, page=0, sort=id, desc=True
[D 230519 02:56:09 base:400] [  146 ms] select books from library  (count = 100)
[D 230519 02:56:09 base:417] [  166 ms] select books from database (count = 100)
[I 230519 02:56:09 web:2239] 304 GET /api/lololo/book/list?page=1&sort=id&desc=true&num=100&search= (172.17.0.1) 189.89ms
[D 230519 02:56:10 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[D 230519 02:56:10 lololo:451] num=100, page=0, sort=id, desc=True
[D 230519 02:56:10 base:400] [  146 ms] select books from library  (count = 100)
[D 230519 02:56:10 base:417] [  166 ms] select books from database (count = 100)
[I 230519 02:56:10 web:2239] 304 GET /api/lololo/book/list?page=1&sort=id&desc=true&num=100&search= (172.17.0.1) 189.47ms
[D 230519 02:56:10 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:10 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 18.83ms
[D 230519 02:56:10 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[D 230519 02:56:10 lololo:451] num=100, page=0, sort=id, desc=True
[D 230519 02:56:10 base:400] [  146 ms] select books from library  (count = 100)
[D 230519 02:56:10 base:417] [  166 ms] select books from database (count = 100)
[I 230519 02:56:10 web:2239] 304 GET /api/lololo/book/list?page=1&sort=id&desc=true&num=100&search= (172.17.0.1) 189.48ms
[D 230519 02:56:12 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:12 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 18.28ms
[D 230519 02:56:12 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[D 230519 02:56:12 lololo:451] num=100, page=0, sort=id, desc=True
[D 230519 02:56:12 base:400] [  148 ms] select books from library  (count = 100)
[D 230519 02:56:12 base:417] [  168 ms] select books from database (count = 100)
[I 230519 02:56:12 web:2239] 304 GET /api/lololo/book/list?page=1&sort=id&desc=true&num=100&search= (172.17.0.1) 191.97ms
[D 230519 02:56:13 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[D 230519 02:56:13 lololo:451] num=100, page=0, sort=id, desc=True
[D 230519 02:56:13 base:400] [  146 ms] select books from library  (count = 100)
[D 230519 02:56:13 base:417] [  166 ms] select books from database (count = 100)
[I 230519 02:56:13 web:2239] 304 GET /api/lololo/book/list?page=1&sort=id&desc=true&num=100&search= (172.17.0.1) 190.07ms
[D 230519 02:56:14 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:14 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 18.44ms
[D 230519 02:56:16 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:16 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 18.32ms
[D 230519 02:56:18 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:18 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 18.08ms
[D 230519 02:56:20 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:20 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 18.84ms
[D 230519 02:56:22 base:218] Query User(1) = <id=1, username=lololo, email=lololo@126.com>
[I 230519 02:56:22 web:2239] 304 GET /api/lololo/import/status (172.17.0.1) 18.49ms

**Comment by talebook** [comment]
看起来像是书籍本身有异常，引起导入失败。请提供下对应到书籍文件。

**Comment by Aetco** [comment]
请提供一下邮箱，我找了一圈没有找到。

**Comment by Aetco** [comment]
> Owner

请提供一下邮箱，我找了一圈没有找到。是否需要问题发生时的相应日志？

**Comment by talebook** [comment]
> > Owner
> 
> 
> 
> 请提供一下邮箱，我找了一圈没有找到。是否需要问题发生时的相应日志？

直接把文件上传到github这里就好。需要提供日志。

**Comment by Aetco** [comment]
> > > Owner
> > 
> > 
> > 请提供一下邮箱，我找了一圈没有找到。是否需要问题发生时的相应日志？
> 
> 直接把文件上传到github这里就好。需要提供日志。

附件为问题文档中的其中一本和全部的日志文件。

日志中所有问题发生处或问题发生附近，文件名中必会出现<0x00>。

如[I 230613 10:36:27 scan:226] import [语言哲学<0x00>] from /data/books/imports/语言哲学__新知文库 25 .pdf

[talebook.log](https://github.com/talebook/talebook/files/13797848/talebook.log)

[语言哲学__新知文库 25 .pdf](https://github.com/talebook/talebook/files/13797836/__.25.pdf)

**Comment by Aetco** [comment]
![截图](https://github.com/talebook/talebook/assets/32085506/48f33879-4a52-447f-8d2f-96f799383036)
截图为sublime text中的现实内容。同时该文件在其他批次的批量上传中并不会出现导入失败的情况。

**Comment by Aetco** [comment]
[talebook.zip](https://github.com/talebook/talebook/files/13798046/talebook.zip)
此为完整日志文件，密码为OPIFU_()P*&%#

**Comment by talebook** [comment]
测试验证，就是这本书识别后书名里会特殊字符\x00，导致程序报错。我晚些加些处理逻辑
