### ISSUE TITLE
打开txt文件超级慢，没有了标签功能。

### ISSUE THREAD

**Issue by magicindex** [talebook/talebook#305]
打开txt文件超级慢，稍微大点容易卡死，需要转圈半天，稍微操作就是又要半天才能缓过来。内部是否有转换器，txt文件转成epub。再就是阅读页面目录太宽了，没有了标签功能。

**Comment by talebook** [comment]
https://github.com/talebook/talebook/pull/326
有个网友单独开发了TXT的阅读功能，在测试中。

**Comment by talebook** [comment]
已在v3.6.6版本中优化
