### ISSUE TITLE
刚开始用talebook，从calibre转过来的。两个问题困扰着我。

### ISSUE THREAD

**Issue by magicindex** [talebook/talebook#306]
1、首页上的所有书籍为什么不是所有书籍按照 名称升序降序 方块模式全部显示出来，而是所有数据跳到分类显示。这样找本数感觉不适应。
2、首页页面思路还是作为在线公共书库来设计的，作为私有书库设计为什不把 自己喜欢的收藏的 和自己正在阅读的，和新上传的放在首页。

其他：阅读页面标签没有了有点困扰，其他字体放大功能非常棒。没有内部转码下载的一些文件如txt在线阅读体验不好，好慢。如果有在线转码跟calibre一样自动转码或者人工转码就好了。

**Comment by talebook** [comment]
这个项目设计初衷的确是公共书库。短期内也不会调整。

1. 如果希望表格式的全量浏览图书，「管理-图书管理」这个页面可以满足你。
2. 放置阅读记录是个很好的建议，我标记下，以后尝试做。
3. 阅读页面是用了单独的插件，所以打通得不是很好。
4. TXT的阅读能力最近有个网友贡献了代码，近期会做下测试验证，发布出来。
