### ISSUE TITLE
/books/imports/ 目录无权限无法拷贝书籍至import目录

### ISSUE THREAD

**Issue by huang5307** [talebook/talebook#307]
我是在Qnap 威联通 利用docker compose的方式建立的，一切正常，但是有一个问题是，我无法把书籍copy到/books/imports/ 目录，我检查了错误信息是没有权限，我试着进去改这个目录的权限，但是权限无法修改，不知道大家是否有遇到这个问题？如何解决？

**Comment by DDSDerek** [comment]
应该是权限问题导致的，程序启动用户为root

**Comment by tommyvinny** [comment]
文件夹权限改为777即可直接拷贝进去，拷贝完了改回775即可
