### ISSUE TITLE
docker版本能否增加puid,guid,umask这三个变量。

### ISSUE THREAD

**Issue by oosoos01** [talebook/talebook#313]
docker版本能否增加puid,guid,umask这三个变量。
主要像unraid这种文件共享用户和root用户是分开的情况，会出现文件夹打不开，提示没有权限的情况。

**Comment by DDSDerek** [comment]
https://github.com/talebook/talebook/pull/278 之前这个PR添加过，但是因为设置目录文件权限文件太多太慢而放弃了，我将重新优化尝试添加
