### ISSUE TITLE
导入了大约4w本书之后，无法批量导入图书

### ISSUE THREAD

**Issue by JackWinston** [talebook/talebook#317]
1，我本地有10w本图书。在导入到第4w本之后，再次点击批量导入，有读条但是无法导入。
2，导入页面批量选择图书的逻辑需要优化。不能直接选择跳到某一页，只能下一页。如果一共有99页，那到最后一页需要点98次下一页。

**Comment by HelloMusician** [comment]
问题一重启服务器即可。问题二等待作者回归或者你可以修改代码解决

**Comment by talebook** [comment]
调大了分页选项，增加了 5000 和  10000 这两个选项，应该够用了。
另，这个前端框架库没有支持【增加一个选页输入框】，懒得弄，所以不会支持第2点了。
