### ISSUE TITLE
有没有什么办法一次性导入11W本扫描完成的书，1000本导入有点没效率

### ISSUE THREAD

**Issue by SUNNY-CT** [talebook/talebook#325]
NAS11万本书已经扫描完成  但是导入成了大问题  目前只能1000本导入一次  等半小时再继续 
试过命令
calibredb add --library-path=/data/books/library/ -r /data/books/imports/
感觉并没有什么事情发生  刷新界面没有图书增加  只看到硬板确实有数据在写入 

各位大佬求指导
![1](https://github.com/talebook/talebook/assets/68763836/0987bd37-1354-4dad-9fc8-001568c64bdb)

**Comment by liaochunho** [comment]
我和你一样 要一次性导入5T的书籍。

**Comment by kelvin-ye** [comment]
我又找到了一个新办法，因为我又找到了4w多本书，之前的方法估计不行了，可靠性太差，速度太慢了。
在nas上安装docker，docker安装Ubuntu desktop容器，用Calibra for Linux 管理即可，目前平均5秒一本书

**Comment by talebook** [comment]
命令行和 WEBUI是不能同时使用的（因为各自会读取到内存中，所以不会实时更新）。等命令行自动处理完，再使用WEBUI就好。

另外，WEB版的导入功能考虑到了文件重复的问题（比如说文件内容相同，但名字不同），做了去重处理；calibre命令行的话，则是根据书籍信息（书名/作者）进行去重
