### ISSUE TITLE
扫描书籍自动去重

### ISSUE THREAD

**Issue by geekidentity** [talebook/talebook#327]
多点了一次扫描书籍，过一会发现之前已经扫描到的又开始重新扫描了，这里是不是可以加个判重。

这里已经80000多本书了，实际是37000多本
![image](https://github.com/talebook/talebook/assets/23332528/7f0af636-22ec-4aac-916d-ca89d272dcd0)

**Comment by talebook** [comment]
默认情况下，重复点击【扫描书籍】是不会产生重复记录的。根据你的截图，你的导入目录似乎调整过，跟书库目录有重叠；建议使用默认的那个导入目录
