### ISSUE TITLE
配置MySQL

### ISSUE THREAD

**Issue by geekidentity** [talebook/talebook#329]
docker-compse 中配置 manual.py，但为啥没有自动创建auto.py， 导致不能正常访问
`
talebook:
    container_name: talebook
    restart: always
    image: talebook/talebook
    volumes:
      - /app/talebook:/data
      - ./manual.py:/data/books/settings/manual.py
`

![image](https://github.com/talebook/talebook/assets/23332528/689433f6-bc46-48e7-a25a-d8c10ee0909f)

**Comment by talebook** [comment]
`auto.py`是在安装时才创建的，如果你没有执行安装过程，那么就不会创建出 `auto.py` 。

建议你检查下 `manual.py`中是否有 `'installed': True`，可以删掉或修改为 `False` ，那么再次进入时就会触发安装流程。
