### ISSUE TITLE
opds通过浏览器可以访问，通过静读天下app报org.apache.http.client.clientProtocolException

### ISSUE THREAD

**Issue by smilesxsy** [talebook/talebook#334]
静读天下app版本为：8.6
手机浏览器可以访问到，怎么可以使用静读天下访问呢

**Comment by smilesxsy** [comment]
linuxserver/calibre-web:0.6.21 提供的opds使用静读天下app是可以访问的

**Comment by talebook** [comment]
请参考：文档中的[「静读天下」APP里访问书库会失败，怎么办？](https://github.com/talebook/talebook/blob/master/document/README.zh_CN.md#%E9%9D%99%E8%AF%BB%E5%A4%A9%E4%B8%8Bapp%E9%87%8C%E8%AE%BF%E9%97%AE%E4%B9%A6%E5%BA%93%E4%BC%9A%E5%A4%B1%E8%B4%A5%E6%80%8E%E4%B9%88%E5%8A%9E)
