### ISSUE TITLE
从互联网同步书籍信息 只显示百度百科的，而且没封面

### ISSUE THREAD

**Issue by apple524** [talebook/talebook#340]
![image](https://github.com/talebook/talebook/assets/44286181/cd537d3e-abe6-41d9-9329-e9c068e27444)

用docker安装的，douban-api-rs  这个也安装了，用网络访问也能访问
![image](https://github.com/talebook/talebook/assets/44286181/6c754c66-0e50-4352-84cb-f4df1a0d33bd)

豆瓣插件API地址(例如 http://10.0.0.1:8080 )   这里也填了
还要从其它什么地方找问题吗？谢谢

**Comment by talebook** [comment]
1. 发一下页面上显示的书名和作者名。
2. 把书籍作为附件传上来，我排查下

**Comment by apple524** [comment]
http://lede.mwifi.top:9011/
这是我搭建的书库
334542110@qq.com
方便给一个邮箱联系吗？

**Comment by frankygtd** [comment]
请问，这个问题怎么解决的？我现在也是同样的问题

**Comment by apple524** [comment]
你这个端口映射出去试试看，我后面搭建的这个douban-rs-api，端口映射出去，外网能打卡，然后系统里面填外网那个地址就可以了

**Comment by frankygtd** [comment]
> 你这个端口映射出去试试看，我后面搭建的这个douban-rs-api，端口映射出去，外网能打卡，然后系统里面填外网那个地址就可以了
我试了，端口映射后，通过浏览器访问可以打开，看到"接口列表"信息，但是还是无法获取书籍信息。
您搭的douban-rs-api用的镜像是ghcr.io/cxfksword/douban-api-rs 么？

**Comment by frankygtd** [comment]
![1715067969011](https://github.com/talebook/talebook/assets/45612096/0d8d0924-932c-45ab-a487-98003c123fe6)

**Comment by frankygtd** [comment]
talebook里面填的就是外网可以访问的那个地址

**Comment by frankygtd** [comment]
搞定了，原来是地址里面多了个 /
