### ISSUE TITLE
如何重置管理员密码？没有设置smtp

### ISSUE THREAD

**Issue by onmpen** [talebook/talebook#353]
除了重装……还有其他办法重置吗

**Comment by talebook** [comment]
修改配置文件 ·books/settings/auto.py· 中的 `installed` 为 `False`，可触发重新安装（主要是重置管理员的信息），同时其他配置信息都会保留。

**Comment by onmpen** [comment]
多谢 已解决

**Comment by onmpen** [comment]
请问是否支持将 批量导入扫描目录 或者  library 目录设置为挂载的 onedrive ？我尝试这样操作，但是不成功。

另外，imports 目录下的书籍被扫描导入后，会存放在 library 下，那 imports 目录下的是不是可以删除了？

**Comment by shenslink** [comment]
> 请问是否支持将 批量导入扫描目录 或者 library 目录设置为挂载的 onedrive ？我尝试这样操作，但是不成功。
> 
> 另外，imports 目录下的书籍被扫描导入后，会存放在 library 下，那 imports 目录下的是不是可以删除了？

我目前就是挂载到onedrive使用的，一开始也不行，折腾很久，后来挂载时增加了权限设置。我是使用alist将onedrive挂载到VPS，然后用rclone，挂载alist的webdav。

**Comment by shenslink** [comment]
高权限的挂载代码供你参考：
rclone mount alist:/OneDrive/talebook /data/talebook --copy-links --allow-other --allow-non-empty --vfs-cache-mode=full --file-perms=0777 --daemon

**Comment by onmpen** [comment]
> 高权限的挂载代码供你参考： rclone mount alist:/OneDrive/talebook /data/talebook --copy-links --allow-other --allow-non-empty --vfs-cache-mode=full --file-perms=0777 --daemon

感谢分享！我试一下。你是挂载到 import 目录还是 library 目录？

**Comment by shenslink** [comment]
> > 高权限的挂载代码供你参考： rclone mount alist:/OneDrive/talebook /data/talebook --copy-links --allow-other --allow-non-empty --vfs-cache-mode=full --file-perms=0777 --daemon
> 
> 感谢分享！我试一下。你是挂载到 import 目录还是 library 目录？

所有数据都挂到onedrive了
