### ISSUE TITLE
导入图书报 504 错。

### ISSUE THREAD

**Issue by Drdajie** [talebook/talebook#356]
# 问题描述
将包含图书的文件夹导入到指定目录，扫描并导入之后报504错误，并后续也无法访问网站。

# 问题环境
- URL：出现异常时的URL
- 运行系统：网站
- 访问设备：Windows
- 浏览器版本：Chrome 版本 120.0.6099.217

# 复现步骤
1. 将包含多个书籍的文件夹导入到 .../imports 文件夹中，并在导入界面点击刷新按钮。
2. 扫描并批量导入
3. 看到报错504

# 截图
![1705310565143](https://github.com/talebook/talebook/assets/30342057/927ae5ad-1fa8-4225-8bfc-5b4b826a12cd)

# 报错信息
第一次报错时让查看日志信息，之后就打不开网页了。

# 日志
[talebook.log](https://github.com/talebook/talebook/files/13937148/talebook.log)

# 书籍文件
所有书籍放到了 books 文件夹中，之后将文件夹放入了 .../imports 目录下，所有书籍都是 pdf 格式。

# 其他
如果是比较复杂的问题，可以把整个书库 `/books/library/metadata.db` 数据库文件上传，以便作者复现异常场景

**Comment by talebook** [comment]
504状态码代表着程序处理超时了，上述日志中没看出异常的原因。可能是python程序直接挂掉了（或者某些原因卡住了），可以再看看docker自身的日志。

**Comment by wuyaoqing** [comment]
跟我一样，刚刚部署ok，将txt文件放在docker主机目录的imports文件夹，导入显示：服务器异常，状态码: 504
请查阅服务器日志:
talebook.log
