### ISSUE TITLE
依然是txt问题,无法导入txt到书库中

### ISSUE THREAD

**Issue by magicindex** [talebook/talebook#360]
# 问题描述
复制txt文件到imports目录，扫描书籍，正常显示，选择并导入书籍，提示:服务器异常，状态码:504  请查阅服务器日志，talebook.log

导入其他文件epub均正常。

# 问题环境
- 群晖docker 系统版本v3.6.8

# 截图
请上传报错的截图

![IMG_20240126_220259.jpg](https://github.com/talebook/talebook/assets/10709078/23fe9ab0-9483-4719-adef-aedd4510779c)

![IMG_20240126_220429.jpg](https://github.com/talebook/talebook/assets/10709078/d5cb7fb1-6102-4465-982f-0bce155219ee)

# 日志
请上传 `talebook.log` 文件，或截取日志中 提示 `Exceptions` 的部分

![IMG_20240126_220818.jpg](https://github.com/talebook/talebook/assets/10709078/f0430f73-4b3b-4f39-9109-965238e20cce)

![IMG_20240126_220755.jpg](https://github.com/talebook/talebook/assets/10709078/a5aa3f13-5442-4c60-a449-bfea8c184a28)

![IMG_20240126_220523.jpg](https://github.com/talebook/talebook/assets/10709078/6de1887c-8700-40da-9bf8-334eadaeda27)

**Comment by magicindex** [comment]
[Uploading talebook.log…]()

**Comment by talebook** [comment]
same as #356 . fixed in v3.7.0
