### ISSUE TITLE
极空间Docker，Calibre PC客户端管理数据库后，Talebook一直显示服务器正在启动中

### ISSUE THREAD

**Issue by Alleparaluiadox** [talebook/talebook#366]
# 问题描述
这几日使用最新版本（应当是3.6.8）的Talebook创建容器，并完成管理员账户注册等。
书库数据库约有2MB大小，使用Calibre PC版客户端管理。在完成管理后，一般重启Talebook服务后就能完成书库导入。但现在一直显示服务器正在启动中。

# 问题环境
- URL：talebook首页
- 运行系统：极空间 Docker
- 访问设备：Windows/ 11
- 浏览器版本：Vivaldi 6.5.3206.63，Chrome/120.0.0.0

# 复现步骤
1. 新创建Talebook容器
2. 使用Calibre PC版本管理书库，将历史书籍导入，将默认书籍删除。
3. 重启容器后，Talebook显示服务器正在启动中。

# 截图
![image](https://github.com/talebook/talebook/assets/29335651/776e02a8-a7c0-4ed7-be61-036270400c1d)

# 报错信息
]2024-02-16T15:24:22.025365030Z 2024-02-16 23:24:22,024 INFO spawned: 'tornado' with pid 5441
�2024-02-16T15:24:23.037692958Z 2024-02-16 23:24:23,037 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:23.274283507Z 2024-02-16 23:24:23,274 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:24.281835971Z 2024-02-16 23:24:24,281 INFO spawned: 'tornado' with pid 5448
�2024-02-16T15:24:25.368337405Z 2024-02-16 23:24:25,368 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:25.600488619Z 2024-02-16 23:24:25,600 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:26.607130476Z 2024-02-16 23:24:26,606 INFO spawned: 'tornado' with pid 5455
�2024-02-16T15:24:27.722289053Z 2024-02-16 23:24:27,722 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:27.981787223Z 2024-02-16 23:24:27,981 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:28.990231613Z 2024-02-16 23:24:28,989 INFO spawned: 'tornado' with pid 5462
�2024-02-16T15:24:29.999972929Z 2024-02-16 23:24:29,999 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:30.231942679Z 2024-02-16 23:24:30,231 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:31.239394504Z 2024-02-16 23:24:31,238 INFO spawned: 'tornado' with pid 5469
�2024-02-16T15:24:32.362176154Z 2024-02-16 23:24:32,361 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:32.619996097Z 2024-02-16 23:24:32,619 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:33.626108052Z 2024-02-16 23:24:33,625 INFO spawned: 'tornado' with pid 5476
�2024-02-16T15:24:34.692144038Z 2024-02-16 23:24:34,691 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:34.923808092Z 2024-02-16 23:24:34,923 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:35.931017822Z 2024-02-16 23:24:35,930 INFO spawned: 'tornado' with pid 5483
�2024-02-16T15:24:36.935313459Z 2024-02-16 23:24:36,935 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:37.166389656Z 2024-02-16 23:24:37,166 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:38.174072232Z 2024-02-16 23:24:38,173 INFO spawned: 'tornado' with pid 5490
�2024-02-16T15:24:39.303312900Z 2024-02-16 23:24:39,303 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:39.560469469Z 2024-02-16 23:24:39,560 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:40.567398575Z 2024-02-16 23:24:40,566 INFO spawned: 'tornado' with pid 5497
�2024-02-16T15:24:41.603059322Z 2024-02-16 23:24:41,602 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:41.861814258Z 2024-02-16 23:24:41,861 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:42.868956692Z 2024-02-16 23:24:42,868 INFO spawned: 'tornado' with pid 5504
�2024-02-16T15:24:43.963553602Z 2024-02-16 23:24:43,963 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:44.195521517Z 2024-02-16 23:24:44,195 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:45.202826069Z 2024-02-16 23:24:45,201 INFO spawned: 'tornado' with pid 5511
�2024-02-16T15:24:46.263765326Z 2024-02-16 23:24:46,263 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:46.521223313Z 2024-02-16 23:24:46,520 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:47.527871496Z 2024-02-16 23:24:47,527 INFO spawned: 'tornado' with pid 5518
�2024-02-16T15:24:48.618888992Z 2024-02-16 23:24:48,618 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:48.851994533Z 2024-02-16 23:24:48,851 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:49.858391072Z 2024-02-16 23:24:49,857 INFO spawned: 'tornado' with pid 5525
�2024-02-16T15:24:50.862003870Z 2024-02-16 23:24:50,861 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:51.095006054Z 2024-02-16 23:24:51,094 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:52.100444799Z 2024-02-16 23:24:52,099 INFO spawned: 'tornado' with pid 5532
�2024-02-16T15:24:53.149181803Z 2024-02-16 23:24:53,148 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:53.387668119Z 2024-02-16 23:24:53,387 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:54.393543312Z 2024-02-16 23:24:54,392 INFO spawned: 'tornado' with pid 5540
�2024-02-16T15:24:55.509016099Z 2024-02-16 23:24:55,508 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:55.740572727Z 2024-02-16 23:24:55,740 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:56.748407635Z 2024-02-16 23:24:56,747 INFO spawned: 'tornado' with pid 5547
�2024-02-16T15:24:57.783889879Z 2024-02-16 23:24:57,783 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:24:58.016243767Z 2024-02-16 23:24:58,015 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:24:59.022631470Z 2024-02-16 23:24:59,022 INFO spawned: 'tornado' with pid 5554
�2024-02-16T15:25:00.041666861Z 2024-02-16 23:25:00,041 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:25:00.278718753Z 2024-02-16 23:25:00,278 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:25:01.283751077Z 2024-02-16 23:25:01,283 INFO spawned: 'tornado' with pid 5561
�2024-02-16T15:25:02.393757152Z 2024-02-16 23:25:02,393 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:25:02.632663238Z 2024-02-16 23:25:02,632 INFO exited: tornado (exit status 1; not expected)
]2024-02-16T15:25:03.639903643Z 2024-02-16 23:25:03,639 INFO spawned: 'tornado' with pid 5569
e2024-02-16T15:25:04.249152774Z 2024-02-16 23:25:04,248 WARN received SIGTERM indicating exit request
W2024-02-16T15:25:04.249404521Z 2024-02-16 23:25:04,249 INFO waiting for tornado to die
e2024-02-16T15:25:04.255124293Z 2024-02-16 23:25:04,254 INFO stopped: tornado (terminated by SIGTERM)
32024-02-16T15:25:05.343943353Z usermod: no changes
e2024-02-16T15:25:05.935973182Z [I 240216 23:25:05 main:127] Init library with [/data/books/library/]
{2024-02-16T15:25:05.936020413Z [I 240216 23:25:05 main:128] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
v2024-02-16T15:25:05.936030817Z [I 240216 23:25:05 main:129] Init Static  with [/var/www/talebook/webserver/resources]
x2024-02-16T15:25:05.936073058Z [I 240216 23:25:05 main:130] Init HTML    with [/var/www/talebook/webserver/../app/dist]
x2024-02-16T15:25:05.936082365Z [I 240216 23:25:05 main:131] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
T2024-02-16T15:25:05.950015623Z [I 240216 23:25:05 models:40] Bind modles._session()
R2024-02-16T15:25:05.974199810Z [I 240216 23:25:05 main:150] Create tables into DB
e2024-02-16T15:25:06.744776450Z [I 240216 23:25:06 main:127] Init library with [/data/books/library/]
{2024-02-16T15:25:06.744824964Z [I 240216 23:25:06 main:128] Init AuthDB  with [sqlite:////data/books/calibre-webserver.db]
v2024-02-16T15:25:06.744837733Z [I 240216 23:25:06 main:129] Init Static  with [/var/www/talebook/webserver/resources]
x2024-02-16T15:25:06.744878863Z [I 240216 23:25:06 main:130] Init HTML    with [/var/www/talebook/webserver/../app/dist]
x2024-02-16T15:25:06.744947204Z [I 240216 23:25:06 main:131] Init Nuxtjs  with [/var/www/talebook/webserver/../app/.env]
Q2024-02-16T15:25:06.744970475Z [I 240216 23:25:06 main:134] updating configs ...
a2024-02-16T15:25:06.746266808Z [E 240216 23:25:06 async_service:88] service register <send_mail>
a2024-02-16T15:25:06.746314719Z [E 240216 23:25:06 async_service:88] service register <send_book>
A2024-02-16T15:25:06.783962810Z [I 240216 23:25:06 main:139] done
82024-02-16T15:25:07.992578691Z Restarting nginx: nginx.
2024-02-16T15:25:08.298860065Z 2024-02-16 23:25:08,298 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
�2024-02-16T15:25:08.298893603Z 2024-02-16 23:25:08,298 INFO Included extra file "/etc/supervisor/conf.d/talebook.conf" during parsing
c2024-02-16T15:25:08.303182418Z 2024-02-16 23:25:08,303 INFO RPC interface 'supervisor' initialized
�2024-02-16T15:25:08.303229996Z 2024-02-16 23:25:08,303 CRIT Server 'unix_http_server' running without any HTTP authentication checking
[2024-02-16T15:25:08.303558933Z 2024-02-16 23:25:08,303 INFO supervisord started with pid 1
[2024-02-16T15:25:09.309900301Z 2024-02-16 23:25:09,309 INFO spawned: 'tornado' with pid 52
�2024-02-16T15:25:10.313572650Z 2024-02-16 23:25:10,313 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:25:10.544192889Z 2024-02-16 23:25:10,543 INFO exited: tornado (exit status 1; not expected)
[2024-02-16T15:25:11.551709513Z 2024-02-16 23:25:11,551 INFO spawned: 'tornado' with pid 59
�2024-02-16T15:25:12.626916001Z 2024-02-16 23:25:12,626 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:25:12.858424627Z 2024-02-16 23:25:12,858 INFO exited: tornado (exit status 1; not expected)
[2024-02-16T15:25:13.866660155Z 2024-02-16 23:25:13,866 INFO spawned: 'tornado' with pid 66
�2024-02-16T15:25:14.869334556Z 2024-02-16 23:25:14,869 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:25:15.104265635Z 2024-02-16 23:25:15,104 INFO exited: tornado (exit status 1; not expected)
[2024-02-16T15:25:16.111268335Z 2024-02-16 23:25:16,110 INFO spawned: 'tornado' with pid 73
�2024-02-16T15:25:17.155719473Z 2024-02-16 23:25:17,155 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:25:17.414691510Z 2024-02-16 23:25:17,414 INFO exited: tornado (exit status 1; not expected)
[2024-02-16T15:25:18.422066434Z 2024-02-16 23:25:18,421 INFO spawned: 'tornado' with pid 80
�2024-02-16T15:25:19.434396346Z 2024-02-16 23:25:19,434 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:25:19.691492311Z 2024-02-16 23:25:19,691 INFO exited: tornado (exit status 1; not expected)
[2024-02-16T15:25:20.697647513Z 2024-02-16 23:25:20,697 INFO spawned: 'tornado' with pid 87
�2024-02-16T15:25:21.718106721Z 2024-02-16 23:25:21,717 INFO success: tornado entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
j2024-02-16T15:25:21.951210252Z 2024-02-16 23:25:21,950 INFO exited: tornado (exit status 1; not expected)
[2024-02-16T15:25:22.958266000Z 2024-02-16 23:25:22,957 INFO spawned: 'tornado' with pid 94

**Comment by Yinghai75** [comment]
我有类似问题，用的是Macbook的Calibre添加了书籍，以前也是重启容器就会出来新加的书。现在也是一直显示服务器正在启动中。
删除容器再重新建容器后才恢复，前边添加的新书可以正常出现。

**Comment by Yinghai75** [comment]
我用的是黑群晖7.1.x， 浏览器换了数个都是同样情况，容器也是latest

**Comment by talebook** [comment]
上传一下 log 目录中的 talebook.log 文件，我检查下启动失败的原因

**Comment by talebook** [comment]
原因是数据库变成只读了（是否是挂载权限不对？）

**Comment by duckeaty** [comment]
同样的问题，怎么解决啊。群晖7.2安装好就这样。

**Comment by vanabel** [comment]
根据你提供的日志信息，问题的根本原因是 Calibre 数据库文件处于只读模式，导致无法进行写操作。这通常与文件或目录的权限设置有关。以下是解决该问题的步骤：

### 1. 检查文件和目录的权限
确保 Calibre 数据库文件和相关目录的权限正确。你需要检查以下路径的权限：
- `/data/books/library`（Calibre 图书馆目录）
- `/data/books/calibre-webserver.db`（数据库文件）

运行以下命令来检查权限：
```bash
ls -ld /data/books/library
ls -l /data/books/calibre-webserver.db
```

如果权限不正确，可以使用以下命令修改权限：
```bash
sudo chmod -R 755 /data/books/library
sudo chmod 664 /data/books/calibre-webserver.db
```

### 2. 检查文件系统是否为只读
如果文件系统被挂载为只读模式，也会导致此问题。你可以通过以下命令检查挂载状态：
```bash
mount | grep /data/books
```

如果挂载为只读，可以尝试重新挂载为读写模式：
```bash
sudo mount -o remount,rw /data/books
```

### 3. 确保运行 Calibre 的用户有权限访问文件
如果 Calibre 是在 Docker 容器中运行的，需要确保容器内的用户（通常是 `PUID` 和 `PGID`）有权访问挂载的目录。你可以通过以下方式设置：
```bash
sudo chown -R <PUID>:<PGID> /data/books
```

### 4. 检查数据库文件是否损坏
如果上述步骤无法解决问题，可能是数据库文件损坏。你可以尝试修复或重新创建数据库：
```bash
calibredb repair_database --with-library /data/books/library
```

如果修复失败，可以尝试从备份中恢复数据库。

### 5. 重启服务
完成上述操作后，重启 Calibre 服务以确保更改生效。

如果问题仍然存在，可以参考 GitHub 上的类似问题，进一步排查原因。
