### ISSUE TITLE
[Suggestion]Consider change name? It is too simple and confusing

### ISSUE THREAD

**Issue by frankyifei** [talebook/talebook#37]
This is a great project. But there is another similar project called Calibre-web. So maybe you can give this one a better name and it will be easier for people to remember. And it will be easier to attract users and contributors. BTW, I cannot even find the project through googling `calibre-webserver`, it gave me Calibre content server and Calibre-web.

**Comment by talebook** [comment]
Do you have any suggestion? I am not good at naming.

**Comment by talebook** [comment]
renamed the my name: talebook, ^_^
