### ISSUE TITLE
希望增加自动批量刮削功能

### ISSUE THREAD

**Issue by Djooxx** [talebook/talebook#374]
# 背景：什么情况下需要这个功能
批量导入图书后,手动一个一个 从互联网获取信息,太麻烦了

# 需求：想要做成什么样子
希望改成自动的, 类似emby的自动刮削电影信息

**Comment by luochen1990** [comment]
也许可以用GPT之类的LLM来实现

**Comment by Crazy-FuQing** [comment]
+1

**Comment by Crazy-FuQing** [comment]
> 也许可以用GPT之类的LLM来实现

导入书籍后自动或批量执行 从互联网同步书籍信息 功能就行

**Comment by luochen1990** [comment]
This project named [ai-powered](https://github.com/luochen1990/ai_powered) might be useful for this purpose.

**Comment by talebook** [comment]
系统设置中已经支持了「自动拉取互联网书籍信息」的选项。
