### ISSUE TITLE
更新nuxtjs配置文件失败！请确保文件的权限为可写入！

### ISSUE THREAD

**Issue by hjf3008** [talebook/talebook#375]
# 问题描述
更新nuxtjs配置文件失败！请确保文件的权限为可写入！

# 问题环境
- 版本号：例如v3.6.1
- URL：[出现异常时的URL](http://192.168.2.57:8081/install)
- 运行系统：CASAOS
- 访问设备：Windows
- 浏览器版本：例如 Chrome 版本 120.0.6099.109
- 书籍信息：如果是特定的书异常，请提供「书名」和「作者名」

# 复现步骤
1. 初始化设置基本信息
2. 点击完成设置
3. 更新nuxtjs配置文件失败！请确保文件的权限为可写入！

# 截图
初始化设置基本信息后体式如下：
更新nuxtjs配置文件失败！请确保文件的权限为可写入！

# 报错信息
更新nuxtjs配置文件失败！请确保文件的权限为可写入！

**Comment by talebook** [comment]
多谢反馈，这个问题已经修复了，还没发版本。

可以忽略这个错误提示。

**Comment by hjf3008** [comment]
<img width="1079" alt="微信图片_20240319082558" src="https://github.com/talebook/talebook/assets/30075608/97988430-f894-4645-9ff4-74515ec00a83">
初始化界面错误只有关闭按钮，无法忽略

**Comment by talebook** [comment]
刚刚打了一个新的版本 v3.7.1 ，你可以试试看
