### ISSUE TITLE
docker镜像过大，可以减小

### ISSUE THREAD

**Issue by hqshi** [talebook/talebook#380]
# 问题描述

Docker Pull的时候发现镜像大小有400兆，查看dockfile发现是apt导致的。可以在安装完成后清理apt缓存，降低镜像层大小

https://www.kuiki.cn/clean-apt-tmp-file-in-dockerfile/

**Comment by talebook** [comment]
https://github.com/talebook/talebook/blob/master/Dockerfile#L48
