### ISSUE TITLE
需求：希望支持外部数据库

### ISSUE THREAD

**Issue by shenshangshang** [talebook/talebook#395]
# 背景：什么情况下需要这个功能
比如说：现在这个sqlite性能堪忧，经常出现database is locked
的情况，高并发情况下性能也不是很好

# 需求：想要做成什么样子
比如说：建议参考某某软件的样子，做一个类似的TXT阅读器；功能可以简单些，最关键是识别出目录，可以每次点击「下一章」进行阅读。
需求：能否支持其他数据库比如mysql,mango等

# 示意图
用 [腾讯文档的流程图](https://docs.qq.com/flowchart/) 绘制示意图，或者 贴一下其他类似软件的截图

**Comment by Oman4** [comment]
支持mysql或者其他数据库的，需要修改配置

**Comment by Oman4** [comment]
https://github.com/talebook/talebook/issues/284

**Comment by shenshangshang** [comment]
可是修改配置只是把用户信息等放到了mysql,书籍的metadata数据还是存在sqlite里面呀，希望的是书籍信息也能支持mysql

**Comment by talebook** [comment]
> 可是修改配置只是把用户信息等放到了mysql,书籍的metadata数据还是存在sqlite里面呀，希望的是书籍信息也能支持mysql

底层是依赖calibre的，所以metadata必须是sqlite。无调整计划。
