### ISSUE TITLE
请问后续是否考虑开发基于armv7l 32 Bit的服务吗

### ISSUE THREAD

**Issue by ic1123** [talebook/talebook#396]
首先，感谢作者的无私付出！
请问一下后续是否会支持armv7l 32 Bit的docker呢？
再次感谢作者的开发，祝您生活顺遂，万事如意！

**Comment by talebook** [comment]
抱歉，我并没有这方面的设备，没有计划支持。你可以自己折腾，有遇到问题的话可以在QQ群里找我，帮助你一起优化
