### ISSUE TITLE
docker 首次启动PGID和PUID设置为1000，一直启动不成功

### ISSUE THREAD

**Issue by HoYin90** [talebook/talebook#412]
# 问题描述
在绿联docker将PGID和PUID设置为1000，首次启动失败

# 问题环境
- 版本号：3.8.1

- 运行系统：绿联NAS DX4600+ ，docker 20.10.16

# 复现步骤
1. 创建容器，/data 目录映射为固态硬盘 /talebook/data,PGID和PUID设置为1000
2. 启动容器，容器启动成功，网页报错
3. PGID和PUID设置为0，容器启动成功，网页正常，完成初始化
4. PGID和PUID设置为1000，容器启动成功，网页正常

# 截图
<img width="625" alt="7EC2CB898399021A0695AF464E4D0897" src="https://github.com/talebook/talebook/assets/16831855/b6cad010-80b3-4b6f-a6f2-7054fec5ee27">

# 日志
[talebook.log](https://github.com/user-attachments/files/15573884/talebook.log)

**Comment by brantzh6** [comment]
一样的问题，群晖DSM 7.1.1-42962 Update 6

![image](https://github.com/talebook/talebook/assets/4461486/62511fb2-939a-4e3d-9ca2-6e31bc5b1e84)

**Comment by snyzf** [comment]
文件夹权限问题。
