### ISSUE TITLE
无法从豆瓣api返回的数据中提取出作者信息

### ISSUE THREAD

**Issue by Crazy-FuQing** [talebook/talebook#418]
# 问题描述
几句话简要描述问题

# 问题环境
- 版本号：v3.6.4
- URL：出现异常时的URL
- 运行系统：NAS/DOCKER/
- 访问设备：Windows/
- 浏览器版本： Chrome 版本 120.0.6099.109
- 书籍信息：如果是特定的书异常，请提供「书名」和「作者名」

# 复现步骤
![image](https://github.com/talebook/talebook/assets/46838021/d3e74eaf-2dc1-4a00-a503-19feb960d821)

有很多作者为Unknown 的书籍 
![image](https://github.com/talebook/talebook/assets/46838021/0067f256-5259-46c5-8938-ead470658c39)
在豆瓣插件中返回的内容没能提取到有效的作者信息

**Comment by Crazy-FuQing** [comment]
https://github.com/cxfksword/douban-api-rs 已经不在维护了 ，作者大大有考虑下换个api吗 github同类型站点很多，跪求回复

**Comment by talebook** [comment]
> https://github.com/cxfksword/douban-api-rs 已经不在维护了 ，作者大大有考虑下换个api吗 github同类型站点很多，跪求回复

@Crazy-FuQing 有推荐的项目吗？

**Comment by asseywang** [comment]
https://hub.docker.com/r/fugary/simple-boot-douban-api @talebook

**Comment by Crazy-FuQing** [comment]
> > https://github.com/cxfksword/douban-api-rs 已经不在维护了 ，作者大大有考虑下换个api吗 github同类型站点很多，跪求回复
> 
> @Crazy-FuQing 有推荐的项目吗？

此问题已解决，我优化了douban-api-rs项目中数据清洗的部分逻辑  https://github.com/Crazy-FuQing/douban-api-rs/releases/tag/v1.0

**Comment by asseywang** [comment]
那怎么用，你要发个新的镜像吗？@Crazy-FuQing

**Comment by Crazy-FuQing** [comment]
> 那怎么用，你要发个新的镜像吗？@Crazy-FuQing

你可以直接下载执行  windows即可

**Comment by asseywang** [comment]
我是Docker里用的，  
`douban-rs-api:
    restart: always
    image: ghcr.io/cxfksword/douban-api-rs`

**Comment by Crazy-FuQing** [comment]
> 我是Docker里用的， `douban-rs-api: restart: always image: ghcr.io/cxfksword/douban-api-rs`

那就进容器终端将bin下的douban-api-rs替换

**Comment by c0ldian** [comment]
请问容器的bin下的douban-api-rs一般在容器的哪个文件夹里

**Comment by c0ldian** [comment]
找到了，但是用`docker cp /volume1/Download/douban-api-rs eallion-douban-api-rs-1:/usr/bin/douban-api-rs`后，重启容器会提示douban-api-rs不存在

**Comment by Crazy-FuQing** [comment]
先建容器再手动复制进去试试？可以求作者大哥把这个打包进[talebook](https://github.com/talebook)，这个issue先关了 有什么问题群里说
