### ISSUE TITLE
书籍导入卡在scan files

### ISSUE THREAD

**Issue by git-shan** [talebook/talebook#419]
# 问题描述
书籍导入过程中，程序卡住了。

# 问题环境
- 版本号：例如v3.8.1
- URL：local
- 运行系统：NAS上的DOCKER
- 访问设备：Mac
- 浏览器版本：例如 Chrome 版本 120.0.6099.109
- 书籍信息：如果是特定的书异常，请提供「书名」和「作者名」
- 
[E 240711 21:59:54 scan:26] save error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: scanfiles.hash
    [SQL: INSERT INTO scanfiles (scan_id, import_id, name, path, hash, status, title, author, publisher, tags, create_time, update_time, book_id, data) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
    [parameters: (1720705337, 0, '爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', '/data/books/imports/ePUBee-backup/06/爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', 'fstat:471646/a2e86455312131e24043531f5f5d25ac', 'new', None, None, None, None, '2024-07-11 21:45:31.767393', '2024-07-11 21:45:31.767416', 0, '{}')]
    (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
    Traceback (most recent call last):
      File "/var/www/talebook/webserver/services/scan.py", line 20, in save_or_rollback
        row.save()
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 82, in save
        self._save_instance(self)
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 64, in _save_instance
        cls._session().commit()
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 597, in commit
        return self._proxied.commit()
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2017, in commit
        trans.commit(_to_root=True)
      File "<string>", line 2, in commit
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
        self._raise_for_prerequisite_state(fn.__name__, current_state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 973, in _raise_for_prerequisite_state
        raise sa_exc.PendingRollbackError(
    sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: scanfiles.hash
    [SQL: INSERT INTO scanfiles (scan_id, import_id, name, path, hash, status, title, author, publisher, tags, create_time, update_time, book_id, data) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
    [parameters: (1720705337, 0, '爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', '/data/books/imports/ePUBee-backup/06/爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', 'fstat:471646/a2e86455312131e24043531f5f5d25ac', 'new', None, None, None, None, '2024-07-11 21:45:31.767393', '2024-07-11 21:45:31.767416', 0, '{}')]
    (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)

**Comment by git-shan** [comment]
程序会反复尝试，但一直卡在这个文件的导入
'/data/books/imports/ePUBee-backup/06/爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub',

(sqlite3.IntegrityError) UNIQUE constraint failed: scanfiles.hash

**Comment by git-shan** [comment]
[E 240711 21:53:19 scan:26] save error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: scanfiles.hash
    [SQL: INSERT INTO scanfiles (scan_id, import_id, name, path, hash, status, title, author, publisher, tags, create_time, update_time, book_id, data) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
    [parameters: (1720705337, 0, '爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', '/data/books/imports/ePUBee-backup/06/爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', 'fstat:471646/a2e86455312131e24043531f5f5d25ac', 'new', None, None, None, None, '2024-07-11 21:45:31.767393', '2024-07-11 21:45:31.767416', 0, '{}')]
    (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
    Traceback (most recent call last):
      File "/var/www/talebook/webserver/services/scan.py", line 20, in save_or_rollback
        row.save()
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 82, in save
        self._save_instance(self)
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 64, in _save_instance
        cls._session().commit()
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 597, in commit
        return self._proxied.commit()
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2017, in commit
        trans.commit(_to_root=True)
      File "<string>", line 2, in commit
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
        self._raise_for_prerequisite_state(fn.__name__, current_state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 973, in _raise_for_prerequisite_state
        raise sa_exc.PendingRollbackError(
    sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: scanfiles.hash
    [SQL: INSERT INTO scanfiles (scan_id, import_id, name, path, hash, status, title, author, publisher, tags, create_time, update_time, book_id, data) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
    [parameters: (1720705337, 0, '爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', '/data/books/imports/ePUBee-backup/06/爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', 'fstat:471646/a2e86455312131e24043531f5f5d25ac', 'new', None, None, None, None, '2024-07-11 21:45:31.767393', '2024-07-11 21:45:31.767416', 0, '{}')]
    (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
[E 240711 21:53:19 scan:26] save error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: scanfiles.hash
    [SQL: INSERT INTO scanfiles (scan_id, import_id, name, path, hash, status, title, author, publisher, tags, create_time, update_time, book_id, data) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
    [parameters: (1720705337, 0, '爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', '/data/books/imports/ePUBee-backup/06/爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', 'fstat:471646/a2e86455312131e24043531f5f5d25ac', 'new', None, None, None, None, '2024-07-11 21:45:31.767393', '2024-07-11 21:45:31.767416', 0, '{}')]
    (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
    Traceback (most recent call last):
      File "/var/www/talebook/webserver/services/scan.py", line 20, in save_or_rollback
        row.save()
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 82, in save
        self._save_instance(self)
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 64, in _save_instance
        cls._session().commit()
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 597, in commit
        return self._proxied.commit()
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2017, in commit
        trans.commit(_to_root=True)
      File "<string>", line 2, in commit
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
        self._raise_for_prerequisite_state(fn.__name__, current_state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 973, in _raise_for_prerequisite_state
        raise sa_exc.PendingRollbackError(
    sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: scanfiles.hash
    [SQL: INSERT INTO scanfiles (scan_id, import_id, name, path, hash, status, title, author, publisher, tags, create_time, update_time, book_id, data) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
    [parameters: (1720705337, 0, '爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', '/data/books/imports/ePUBee-backup/06/爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', 'fstat:471646/a2e86455312131e24043531f5f5d25ac', 'new', None, None, None, None, '2024-07-11 21:45:31.767393', '2024-07-11 21:45:31.767416', 0, '{}')]
    (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
[E 240711 21:53:19 scan:26] save error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: scanfiles.hash
    [SQL: INSERT INTO scanfiles (scan_id, import_id, name, path, hash, status, title, author, publisher, tags, create_time, update_time, book_id, data) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
    [parameters: (1720705337, 0, '爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', '/data/books/imports/ePUBee-backup/06/爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', 'fstat:471646/a2e86455312131e24043531f5f5d25ac', 'new', None, None, None, None, '2024-07-11 21:45:31.767393', '2024-07-11 21:45:31.767416', 0, '{}')]
    (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
    Traceback (most recent call last):
      File "/var/www/talebook/webserver/services/scan.py", line 20, in save_or_rollback
        row.save()
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 82, in save
        self._save_instance(self)
      File "/usr/local/lib/python3.9/dist-packages/social_sqlalchemy/storage.py", line 64, in _save_instance
        cls._session().commit()
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 597, in commit
        return self._proxied.commit()
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2017, in commit
        trans.commit(_to_root=True)
      File "<string>", line 2, in commit
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
        self._raise_for_prerequisite_state(fn.__name__, current_state)
      File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 973, in _raise_for_prerequisite_state
        raise sa_exc.PendingRollbackError(
    sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: scanfiles.hash
    [SQL: INSERT INTO scanfiles (scan_id, import_id, name, path, hash, status, title, author, publisher, tags, create_time, update_time, book_id, data) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
    [parameters: (1720705337, 0, '爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', '/data/books/imports/ePUBee-backup/06/爱伦·坡短篇小说选 (Selected Short Stories by Edgar Allan Poe) (3).epub', 'fstat:471646/a2e86455312131e24043531f5f5d25ac', 'new', None, None, None, None, '2024-07-11 21:45:31.767393', '2024-07-11 21:45:31.767416', 0, '{}')]
    (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)

log file 持续增大，

**Comment by SunRain** [comment]
同样的错误

**Comment by talebook** [comment]
这个报错，是因为有相同文件的书籍（但估计在不同目录），导致计算出来的哈希值冲突了。代码中其中会检测这种冲突并跳过的，不知为啥没生效。 解决方法只能是手动删掉这本报错的数据，再重启了。
