### ISSUE TITLE
从kindle上运行 “体验版浏览器” 无法显示页面

### ISSUE THREAD

**Issue by HenXian** [talebook/talebook#42]
是否可以解决一下这个问题？
我直接在kindle上，用体验版浏览器， 打开网站的时候，页面是空白，什么都没有显示。
在ipad，pc上，则显示正常。

**Comment by lawipac** [comment]
Kindle浏览器对 Javascript 不完全支持。

**Comment by talebook** [comment]
`v3.5.x`系列改为了服务端渲染页面，理论上能支持kindle浏览器了。
