### ISSUE TITLE
点击阅读，随后一直就是“解压完毕，正在打开阅读界面”

### ISSUE THREAD

**Issue by IrisLoveGithub** [talebook/talebook#426]
某书籍，点击阅读按钮后，新打开的页面一直显示的是““解压完毕，正在打开阅读界面”，无限期。。。

# 问题环境
- 版本号：v3.8.1
- URL：出现异常时的URL
- 运行系统：DOCKER
- 访问设备：Windows/Android11等
- 浏览器版本：例如 Chrome 版本 128.0.6613.114，Firefox v129.0.2

**Comment by Jerryplus** [comment]
一样的问题

**Comment by stonekingsy** [comment]
同样docker部署，用家里淘汰的Nuxes 7打开talebook网页就是你说的这个问题， 但是用电脑，或者手机就没有问题。所以推测是Nuxex 7的Android版本过低以及或者内存太小等原因？
