### ISSUE TITLE
无法刮削

### ISSUE THREAD

**Issue by kylinApple** [talebook/talebook#427]
我在docker部署了talebook，也部署了douban-api-rs，在书籍刮削时候网页会卡死返回504错误。
<img width="996" alt="Snipaste_2024-09-09_23-10-20" src="https://github.com/user-attachments/assets/1818670c-9f6a-4618-9e20-e27be974f47e">
然后我查看日志发现如下：
<img width="1377" alt="Snipaste_2024-09-09_23-11-38" src="https://github.com/user-attachments/assets/76e608e6-87d7-410f-87cd-fcaecd7138b3">
开始以为是api问题，但是我单独测试api是能正常运行的，我能访问到自己部署的api：
<img width="300" alt="Snipaste_2024-09-09_23-12-46" src="https://github.com/user-attachments/assets/7af8a781-6a55-4152-ba1f-848980be3e8a">
我找了一本书测试，通过url也能看到是有刮削到的：
<img width="1686" alt="Snipaste_2024-09-09_23-14-21" src="https://github.com/user-attachments/assets/a35171bb-6900-43ea-8791-8801ad02c9db">
所以请教下是哪里出了问题呢？

**Comment by stonekingsy** [comment]
我上周刚装的talebook， 昨天才部署的douban-api-rs，都是部署在docker里面。上传单本书然后从豆瓣更新图书信息是没问题的。不懂你说的刮削是什么， 是大批量更新所有的图书信息么？ 是不是API的调用次数超过限制了？

**Comment by talebook** [comment]
你这个应该是启动的方式不对，两个docker之间没有互通，所有talebook访问douban api失败了。你可以参考项目中自带的 docker-compose.yml 的写法：https://github.com/talebook/talebook/blob/master/docker-compose.yml
