### ISSUE TITLE
最新docker镜像搭建无法注册

### ISSUE THREAD

**Issue by wutaoll** [talebook/talebook#428]
群晖7.2.2，docker 镜像拉取的3.8.1最新镜像，搭建好了之后进入书库要求注册管理员信息，然后一直注册失败，也不清楚是镜像问题还是群晖问题，有没有复现这个问题的朋友，反馈一下怎么处理，卡好几天了

![image](https://github.com/user-attachments/assets/6cbc8d13-7778-498b-aa54-d5a350941e86)

**Comment by talebook** [comment]
提供一下日志

**Comment by wutaoll** [comment]
[talebook.log](https://github.com/user-attachments/files/16947847/talebook.log)

不好u意思我不太会用github ^^，原来可以直接上传log文件的，权限好像是正常的

**Comment by talebook** [comment]
日志里报错`sqlite3.OperationalError: attempt to write a readonly database` ，这是文件权限不正确。建议检查目录权限，或者删掉整个data目录重新安装

**Comment by wutaoll** [comment]
好的，谢谢大佬，应该是群晖7.2.2的问题了，明明权限都给了，docker里也开了高权限执行，就是注册不了，我再试试

**Comment by wutaoll** [comment]
搞了大半夜终于搞好了，感谢大佬帮忙分析。  原因也说一下，后面有遇到同样问题的也好解决： 群晖7.2及以上的系统，组建硬盘存储池的硬盘格式不能选ext4，否则很多应用的权限会出现问题，必须选用btrfs的格式才行，太坑了呀，害我折腾好几天。 奇怪的是一同搭建的docker内的 postgres数据库、joplin和青龙容器没有出现权限问题
