### ISSUE TITLE
从豆瓣API更新信息出错

### ISSUE THREAD

**Issue by zcxgs** [talebook/talebook#442]
# 问题描述
不管是设置信息，还是设置图片及信息，都会出错，不同的书本都是。
信息能更新到，但是点击设置之后就出错了，信息如下。
谢。

# 问题环境
- 版本号：例如v3.8.2
- URL：出现异常时的URL
- 运行系统：极空间+DOCKER
- 访问设备：chrome

# 报错信息
Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 49, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 76, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 195, in post
    refer_mi.cover_data = None
AttributeError: 'NoneType' object has no attribute 'cover_data'

Exception:
Traceback (most recent call last):
  File "/var/www/talebook/webserver/handlers/base.py", line 49, in do
    rsp = func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/base.py", line 76, in do
    return func(self, *args, **kwargs)
  File "/var/www/talebook/webserver/handlers/book.py", line 196, in post
    if len(refer_mi.tags) == 0 and len(mi.tags) == 0:
AttributeError: 'dict' object has no attribute 'tags'

**Comment by talebook** [comment]
你用的豆瓣镜像有问题。系统设置里有提醒的。

**Comment by zcxgs** [comment]
你好，我删除原来的，然后更改为talebook/douban-api-rs后，结果豆瓣的信息都出不来了，只有一个意义不大的百度百科。
如图，谢。
![Screenshot 2024-10-31 220422](https://github.com/user-attachments/assets/ddcb5557-039a-4d64-8682-9bed0cd1ab98)
![Screenshot 2024-10-31 220428](https://github.com/user-attachments/assets/f004cd02-b995-43c4-a198-1d44a927f9e4)
![Screenshot 2024-10-31 220615](https://github.com/user-attachments/assets/5b00f859-e578-44d5-8419-0df09c7eafde)
![Screenshot 2024-10-31 220734](https://github.com/user-attachments/assets/715eaa1c-5dc8-40af-b7c2-ba6c20fa4408)
![Screenshot 2024-10-31 220738](https://github.com/user-attachments/assets/4d7571a3-e691-4efd-8b97-9a8a27a6c80d)
![Screenshot 2024-10-31 220740](https://github.com/user-attachments/assets/cc909708-6a1b-42d0-bdc9-3c978a57c1dc)

**Comment by zcxgs** [comment]
我试了很多次，发现是有些书可以，有些书不行，但是豆瓣上其实都又的，大概率是跟我的文件有关系吧。谢谢。
