### ISSUE TITLE
手机端网页在线观看epub电子书无法翻页

### ISSUE THREAD

**Issue by gaoshulaoshi** [talebook/talebook#457]
![微信图片_20241128175503](https://github.com/user-attachments/assets/627c7098-1711-416a-adca-5d6bcf8072c9)
点按边缘两边无法翻页，边缘滑动翻页的话会一下子翻几页，翻页很不好用，拉取的是最新的docker镜像

**Comment by talebook** [comment]
应该是有浏览器兼容性问题。过几天修一修

**Comment by wuyufeng1989** [comment]
@talebook 大佬，这个问题什么时候修复下

**Comment by talebook** [comment]
> @talebook 大佬，这个问题什么时候修复下

前面的版本已经修复了。现在还有问题？

**Comment by wuyufeng1989** [comment]
> > @talebook 大佬，这个问题什么时候修复下
> 
> 前面的版本已经修复了。现在还有问题？

我用的docker部署的3.8.4，手机用edge，chrome都有这个问题

**Comment by wuyufeng1989** [comment]
> > @talebook 大佬，这个问题什么时候修复下
> 
> 前面的版本已经修复了。现在还有问题？

在平板和PC端没问题
