### ISSUE TITLE
无法在线阅读PDF格式

### ISSUE THREAD

**Issue by KITblue** [talebook/talebook#46]
1.我发现当前可以在线阅读epub，mobi，azw3格式电子书，但是pdf格式却不支持，希望增加对PDF格式的支持。毕竟pdf格式的电子文档量还是相当大的。

pdf格式无法显示：
![image](https://user-images.githubusercontent.com/68754977/88429787-d920ae00-ce29-11ea-8988-f49faf955a16.png)

2.IE内核浏览器无法打开网站；
3.再就是手机端（安卓）无法正常显示在线阅读的内容。

**Comment by luning2016** [comment]
我也觉得能支持pdf就完美了

**Comment by LGinC** [comment]
最新版已支持,不过是调用浏览器解析的,如果浏览器不支持pdf那就没办法了.
常规的edge chrome都支持直接在浏览器打开pdf
