### ISSUE TITLE
推送UI改进建议

### ISSUE THREAD

**Issue by KITblue** [talebook/talebook#47]
现在的推送界面：

![image](https://user-images.githubusercontent.com/68754977/88430339-e0948700-ce2a-11ea-85de-215e6c191545.png)

这会让人误解必须等待推送完成后，窗口自动关闭，而中途关闭会造成推送结束的误解。
测试发现推送kindle实际上是后台进行的，可以关闭窗口。希望更改为提示窗口，比如“书籍xxxxxx已在后台推送”，然后倒计时自动关闭窗口。

**Comment by zhongwei-li** [comment]
确实，后来我才发现可以直接关闭的
