### ISSUE TITLE
批量导入出现错误

### ISSUE THREAD

**Issue by lejitao2013** [talebook/talebook#50]
我在批量导入大概10G电子书的时候，无法导入
![微信图片_20200823220843](https://user-images.githubusercontent.com/61481263/90980335-3b85df00-e58d-11ea-8f7f-174c0f657503.png)

**Comment by lgyjg** [comment]
试下用：

```shell
calibredb add --library-path=/data/books/library/ -r /data/books/upload/ --duplicates
```

**Comment by talebook** [comment]
`v3.5.6`版本支持了批量导入的界面，不在需要使用命令行了。
