### ISSUE TITLE
是否能用calibre 64bit - E-book management  编辑并上传呢  这样好像很方便

### ISSUE THREAD

**Issue by yhwl8888** [talebook/talebook#60]
是否能用calibre 64bit - E-book management  编辑并上传呢  这样好像很方便 测试了两次批量上传都报错

![image](https://user-images.githubusercontent.com/48284412/101571247-a8c16100-3a12-11eb-88a9-1ea022e35084.png)

**Comment by talebook** [comment]
不支持这个功能呢。 使用PC版的话，应该是处理完毕后，把数据库直接拷贝到web版

**Comment by toniexly** [comment]
> 
所以，是可以直接与calibre共用数据库对吗？

**Comment by talebook** [comment]
> > 
> 
> 所以，是可以直接与calibre共用数据库对吗？

可以共享。但是使用PC版编辑后，需要重启web版
