### ISSUE TITLE
上传的电子书大小限制无法修改

### ISSUE THREAD

**Issue by guojunjie4SD** [talebook/talebook#61]
利用docker安装了webserver后，根据提示修改了/etc/nginx/cond.f/calibre-webserver.conf中关于client_max_body_size部分，修改为1000m.  重启所有服务后，上传一个106m的pdf仍然显示失败。

**Comment by talebook** [comment]
具体报错内容是什么？

**Comment by LGinC** [comment]
`[I 211015 11:58:18 http1connection:253] Malformed HTTP message from 172.17.0.1: Content-Length too long`
这个文件110m  通过环境变量设置的client_max_body_size是500m

**Comment by talebook** [comment]
已取消NGINX的限制。并增加了tornado的配置选项。可进入管理员界面的高级选项中修改。
