### ISSUE TITLE
opds不能用

### ISSUE THREAD

**Issue by jxjxjhjh** [talebook/talebook#63]
用软件不能打开opds，显示网络错误，直接打开链接可以。应该是opds里面的链接用相对路径造成的问题吧？

**Comment by talebook** [comment]
我使用kybooks是能正常的。
opds接口，之前有过bug；后来已经都修复了，请更新到最新版试试。

**Comment by jxjxjhjh** [comment]
org.apache.http.client.clientprotocolexception

提示这个是什么意思？
