### ISSUE TITLE
上传错误,点击上传后都没让进行文件选择就直接弹错误

### ISSUE THREAD

**Issue by leishenailong** [talebook/talebook#71]
没办法使用上传，用的是docker布置,命令是:
```
docker run -d --name calibre -p 8001:80 -v /www/wwwroot/book/data:/data talebook/calibre-webserver
```
错误为
```
Exception:
Traceback (most recent call last):
  File "/var/www/calibre-webserver/webserver/handlers/base.py", line 54, in do
    try: rsp = func(self, *args, **kwargs)
  File "/var/www/calibre-webserver/webserver/handlers/base.py", line 74, in do
    return func(self, *args, **kwargs)
  File "/var/www/calibre-webserver/webserver/handlers/book.py", line 432, in post
    postfile = self.request.files['ebook'][0]
KeyError: 'ebook'
```

**Comment by talebook** [comment]
是最新版吗？这应该是历史某个版本出现的BUG



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: leishenailong ***@***.***&gt;
发送时间: 2021年4月24日 22:17
收件人: talebook/talebook ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[talebook/talebook] 上传错误,点击上传后都没让进行文件选择就直接弹错误 (#71)





 
没办法使用上传，用的是docker布置,命令是:
 docker run -d --name calibre -p 8001:80 -v /www/wwwroot/book/data:/data talebook/calibre-webserver  
错误为
 Exception: Traceback (most recent call last):   File "/var/www/calibre-webserver/webserver/handlers/base.py", line 54, in do     try: rsp = func(self, *args, **kwargs)   File "/var/www/calibre-webserver/webserver/handlers/base.py", line 74, in do     return func(self, *args, **kwargs)   File "/var/www/calibre-webserver/webserver/handlers/book.py", line 432, in post     postfile = self.request.files['ebook'][0] KeyError: 'ebook'

**Comment by leishenailong** [comment]
> 是最新版吗？这应该是历史某个版本出现的BUG 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: leishenailong ***@***.***&gt; 发送时间: 2021年4月24日 22:17 收件人: talebook/talebook ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[talebook/talebook] 上传错误,点击上传后都没让进行文件选择就直接弹错误 (#71) 没办法使用上传，用的是docker布置,命令是: docker run -d --name calibre -p 8001:80 -v /www/wwwroot/book/data:/data talebook/calibre-webserver 错误为 Exception: Traceback (most recent call last): File "/var/www/calibre-webserver/webserver/handlers/base.py", line 54, in do try: rsp = func(self, *args, **kwargs) File "/var/www/calibre-webserver/webserver/handlers/base.py", line 74, in do return func(self, *args, **kwargs) File "/var/www/calibre-webserver/webserver/handlers/book.py", line 432, in post postfile = self.request.files['ebook'][0] KeyError: 'ebook' — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是最新版的，特意去文渊阁试了下发现那边也一样，暂时靠手动上传的方式更新书库，就是不怎么方便。

**Comment by talebook** [comment]
请把你的操作步骤详细描述下吧，最好有对应的截图。
