### ISSUE TITLE
群晖安装，要想修改一些图片，模板，应该挂载那些目录？

### ISSUE THREAD

**Issue by ctrol** [talebook/talebook#72]
目前就添加了/data目录，看不到var/www系统文件，像首页的二维码等都不能更改，请问如果想修改，应该怎么做？

**Comment by talebook** [comment]
https://github.com/talebook/talebook/blob/master/document/INSTALL.zh_CN.md#logo


可以参考这个文档



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ctrol ***@***.***&gt;
发送时间: 2021年4月27日 21:35
收件人: talebook/talebook ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[talebook/talebook] 群晖安装，要想修改一些图片，模板，应该挂载那些目录？ (#72)





 
目前就添加了/data目录，看不到var/www系统文件，像首页的二维码等都不能更改，请问如果想修改，应该怎么做？
