### ISSUE TITLE
用户头像无法显示，且无法修改

### ISSUE THREAD

**Issue by lgyjg** [talebook/talebook#75]
首页右上角用户头像无法显示。
进入用户中心-头像-点击修改，无法上传新头像

**Comment by talebook** [comment]
头像用的是gravatar这个网站的功能。貌似被GFW了

**Comment by talebook** [comment]
多谢反馈。v3.5之后已经调整为中国境内的gravatar服务器了，能正常加载头像了。

关于上传新头像的问题：头像功能目前使用的是公共头像服务，所以只能到gravatar平台去修改。暂无计划自己实现一个头像功能。
