### ISSUE TITLE
个别书籍打开时报错 Internal Server Error

### ISSUE THREAD

**Issue by Khaleesi01** [talebook/talebook#87]
Docker版的安装好了，内置的其他书都可以阅读。只有 財富背後的法律密碼 打开是显示 ：500: Internal Server Error
请问这个是什么原因，怎么解决呀？
之前（网页）手动上传了一个 mobi的也是这个错误，删除后，上传了一个epub的可以看

**Comment by talebook** [comment]
书籍文件可能有问题。请提供附件
