### ISSUE TITLE
用户能否设置删除功能（现在只能禁用登陆）

### ISSUE THREAD

**Issue by mayuyu1994** [talebook/talebook#89]
<img width="161" alt="WX20211004-234327@2x" src="https://user-images.githubusercontent.com/20795142/135883190-cd340763-00c2-4b2c-9c74-b070e1081fc7.png">

**Comment by mayuyu1994** [comment]
补充一下禁用登陆貌似是失效的

**Comment by talebook** [comment]
已支持该特性
