### ISSUE TITLE
静读天下app读取opds有问题

### ISSUE THREAD

**Issue by gracehuahua** [talebook/talebook#91]
静读天下可以连接opds，但是点击最新添加等明细会报异常
org.apache.http.client.ClientProtocolExceptiom

**Comment by talebook** [comment]
已优化。
https://github.com/talebook/talebook/blob/master/document/INSTALL.zh_CN.md#%E9%9D%99%E8%AF%BB%E5%A4%A9%E4%B8%8Bapp%E9%87%8C%E8%AE%BF%E9%97%AE%E4%B9%A6%E5%BA%93%E4%BC%9A%E5%A4%B1%E8%B4%A5%E6%80%8E%E4%B9%88%E5%8A%9E

**Comment by xiaoweihong** [comment]
关闭「私人图书馆」模式。
打开「允许任意下载」（访客无需注册或登录）

这两个选项的话，会不安全，没有其它方式解决这个问题么

**Comment by wk-coder** [comment]
> 关闭「私人图书馆」模式。 打开「允许任意下载」（访客无需注册或登录）
> 
> 这两个选项的话，会不安全，没有其它方式解决这个问题么

@xiaoweihong  请问这么长时间解决了吗
