### ISSUE TITLE
用的docker程序，反代域名，域名网站无法登陆账号，只有ip:8080才能登陆账号！

### ISSUE THREAD

**Issue by weiguanght** [talebook/talebook#93]
如题。

**Comment by talebook** [comment]
是不是反向代理没设置正确的头部？？

可以参考这个配置https://github.com/talebook/talebook/blob/master/conf/nginx/calibre-webserver.conf.template

**Comment by weiguanght** [comment]
好的，非常感谢大佬！

**Comment by weiguanght** [comment]
测试了一下，貌似开启缓存才会登陆不了。
