### ISSUE TITLE
chrome浏览器无法正常下载书籍

### ISSUE THREAD

**Issue by weiguanght** [talebook/talebook#95]
多个平台众多浏览器测试下来，发现chrome浏览器安卓、mac端均已测试无法正常下载书籍，得新标签页打开下载链接才能下载。

**Comment by weiguanght** [comment]
后面又试了一下，ip:8080 的网站chrome才能直接下载。

**Comment by WarwickJiang** [comment]
我也是安卓Chrome，在网站中无法下载书籍，下载时会打开新网页，然后自动关闭

**Comment by Ivan314** [comment]
今天试了一下chrome可以下载书籍了

**Comment by talebook** [comment]
无法复现此问题。暂时关闭掉此issue
