### ISSUE TITLE
反向代理docker ip:8090 上传书籍413报错

### ISSUE THREAD

**Issue by weiguanght** [talebook/talebook#97]
上传32.4MB书籍，calibre-webserver-error.log 显示：

2021/11/06 13:45:28 [错误] 31#31：*1726 客户端打算发送太大的正文：32366321 字节，客户端： IP地址，服务器：_，请求：“POST /api/book/upload HTTP/1.0”，主机：“域名”，引荐来源：“网址”

2021/11/06 13:45:28 [error] 31#31: *1726 client intended to send too large body: 32366321 bytes, client: IP地址, server: _, request: "POST /api/book/upload HTTP/1.0", host: "域名", referrer: "网址"

**Comment by talebook** [comment]
413的异常，是因为之前的版本默认给nginx设置了30MB的上限，所以会报错。虽然文档里有调整的方法，但是大部分人都不会去查阅，因此在当前的版本中，已取消nginx的限制；额外提供了「文件上传大小限制」的选项（默认为100MB，对应到代码中是tornado上传的限制，issue#61）。可以进去管理员界面，在高级选项中调整。

**Comment by iJayscn** [comment]
> 413的异常，是因为之前的版本默认给nginx设置了30MB的上限，所以会报错。虽然文档里有调整的方法，但是大部分人都不会去查阅，因此在当前的版本中，已取消nginx的限制；额外提供了「文件上传大小限制」的选项（默认为100MB，对应到代码中是tornado上传的限制，issue#61）。可以进去管理员界面，在高级选项中调整。

此问题在最新版docker镜像里还是 限制20m，需要手动修改 env，NGINX_CLIENT_MAX_BODY_SIZE 设置

**Comment by talebook** [comment]
3.5.X 版本里面已经移除该环境变量了，nginx中不再限制上传大小。
但是，在server中会有限制，可以在设置中心里调整。

**Comment by iJayscn** [comment]
> 3.5.X 版本里面已经移除该环境变量了，nginx中不再限制上传大小。 但是，在server中会有限制，可以在设置中心里调整。

不好意思，拉错镜像了 
talebook/calibre-webserver
