### ISSUE TITLE
推送到kindle过程中出现报错

### ISSUE THREAD

**Issue by mrchen980531** [talebook/talebook#98]
您好，我是在VPS上通过docker安装你提供的calibre-web，但是在设置好smtp后进行测试和推送到kindle过程中会报错。
        原谅我linux不太熟悉，不太理解是哪一步出现了问题，自己通过百度和谷歌查了半天也没能解决。不过smtp的账户和密码应该没有问题。
        我试过gmail，qq以及163邮箱的smtp都会报错，应该是我哪一步没有设置好。望您能够解疑答惑，万分感谢。附件是报错的具体代码。

<img width="809" alt="iShot2021-12-10 16 36 55" src="https://user-images.githubusercontent.com/67358826/145543237-3c924086-06dc-4423-af6e-52cae7401543.png">
<img width="896" alt="iShot2021-12-10 16 37 32" src="https://user-images.githubusercontent.com/67358826/145543257-d6c0eec8-1231-455a-97a7-5a3a4463b3c8.png">
。

**Comment by zhongwei-li** [comment]
你要先去设置里面填一下smtp发送邮箱，找个自己的邮箱（比如网易QQ等）填一下smtp服务器和账号密码

**Comment by mrchen980531** [comment]
已经成功解决了，最后发现是vps主机商没有开放端口25，才导致vps不能通过连接不到外面的smtp服务器，发邮件和客服沟通了之后，一切都解决了。
        说实话，一开始我用ubuntu的docker安装之后发现不行，以为是smtp没有设置好一连换了几个邮箱。其次以为是docker的网络没有设置好，最后又打算使用手动安装，瞎折腾了一大通也不行。最后换了centos后也报错，但是这个通过查询这个报错代码启迪了我是不是端口没有设置好。
        因为我一开始就通过宝塔面板--安全把端口25，465，587等都放行了，就根本没想到是端口的事情。但是后来通过talnet smtp.gmail.com 25失败，才发现是主机商把这个端口关闭了，这半个月的折腾虽说有点戏剧性，但是确实学到了不少关于linux和python的东西。
       最后十分感谢博主的项目和解疑答惑，祝越来越好。
